apiVersion: v1
kind: ConfigMap
metadata:
    name: home-assistant-helm-chart-values
    namespace: home-assistant
data:
    values.yaml: ENC[AES256_GCM,data:5d00+Tp1i6vs5xtgAqjlFIswyKUdyN2Th1ZGmdMFhktbWmGptCZ29zob9zIZbGRmoLeXDfdeW0Jq6phLpRKCYNXbkMxOQ/Cy8vTJl8M8qHQPWntR80yWOwy6TWxd8L3Oh2NtthMErXeu88PNAzryrb9ZnEMe5sRvOrjShWkUOtbtsrJO8e446Ebprs9i8zItJCDXWxHF1NPto6v0cTrShvipHHxjFx2KoiqWl0NIZuNW/8WiYI55cytEpv2iybNOURY9L4cb/pfkFYnVucPxJH4D7vUgsvChXZS16aa5yffzvroZZ+57CJpsMYicKpMFwdpnWzig6QOY/BW/RGe4xvgdBDyOuJQt9qrZ8M2yIigQy3m3ixg0YgRSQon5mRBG3t8wkSE+ORsTnRiYLYzJPCwoI7hkrW+DWq/sBQVZcaYXTtp4hCiGi5vNwrLeHvwEnCuv7egtmfqccyONQETohA9obbxv9hpF1PsHvJyZC839PSnqtOS8GwwoTBjlIZJZC+H5SzZ42DkLFLjbXU3L66mMyDa4viJ21NGOI+WLwmWZpalOmeWLLn/lSvFw+Ty+JoS+onPvbTP8PwWr3she2IVpvqZHV9DEAbiomtgtiTMoJO51lbK2IZmrP+1v05dYLxd05M+5ryWVXFF5YQoNgTfd2KyO9lbKyBOily1+VOn19XNiwLpiJO93dndbnAeII5G2BQ3g7HZ1DJY2UUbXdrQsor2Qb+AyACGX/6AHZFZ1fcaZfaTRUsCbGiSIq9+odvwKJLiJI29dG53eGfk+JtsSzaxTYWMuxPcKzZDYHGwY7jYEixKeJuG2glGoLlc5Ik0qCeahyCsrquoRiftPGyoOLZeexD9hefwBI9U5KLpb9bykguXpbr3pkbQu29jkHybu5kuPijW9v+nY2B7aANhaj2/G1fHQcATETEWZBN9DzmbRJOMKdIzcWUETzsuQtUKpb9kxKgQWlPo8aR+2huG0q7JRmYkK956ZFSXLyRJmnQGsmqZ+u9+YimCAndGLX2jXc2qtdMavQtGdg2QP8ozdrIdyn40hhKCkEffejagWqu6UoOcxzzrM5R3qDmztI1CnY9ruCxA+zEG1VT6bvVKPjw31hAM1f+QVJoHeKhy1u/1h/K4P0RcZhvtiknM=,iv:eBE4UFnrH+LwAnmOP6nIyPgH1HaIvDQ7ZJe9b4QlkVY=,tag:KrwcaC8bOiPLyzZtR/kXUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaC9CbE1XOW1mbCsreDNG
            aHpZK2VTdzhVTkNraDh1ZFNyMStNMkN4VFdJCmJ1dzVBYTNnbzJMcnM1ZzF4SXVs
            ZGs3RzBNYmNOQ2kwRDBxNHhnZUNUdlEKLS0tIDdKVHZjN0JCMTd3QjQ5MjRaU2Fo
            ZWFHS0FqTVB3SXpYc21DOFY0WU5DUGsKxcqCxFnKOlNft1Ws1e7PuC9RHPNLvzzB
            EkE5YbSB/r/9sPyNGnVQALXccEmZtajHOYEwJRFEmw8nWhrA++QfYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-01T07:12:25Z"
    mac: ENC[AES256_GCM,data:CllY128SY70C8bDmY+aesGZ6don6r2VqOdNPYRcmJKcmDS7Zjb+6/CkguSkJsgBJedrTHatA+jXaX5TpipzQC6hp2cf1y0Oq/5U8Ekxkzdz8rjCbehEVedVGOA/kv6zcQKu+UMgmEzG2GCp3MThDH6EdKhlzxBEQm/Few5Rz0wA=,iv:mGoNheTFLRJMI/gMG5xcrfD2DFSq8xdLtJQXMxmi+JU=,tag:Wi5U5xxNcr3iTjA3Z+nGUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
