apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pajikos
  namespace: home-assistant
spec:
  interval: 12h
  url: https://pajikos.github.io/home-assistant-helm-chart/
