---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vkms
spec:
  interval: 30m
  releaseName: vkms
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: vkms
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: vkms-helm-chart-values
      valuesKey: values.yaml
