apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
type: Opaque
stringData:
    botToken: ENC[AES256_GCM,data:PxM3faWqBICBWspklGX2307Y/AocDX3OCbspvEVwi7yV6E6KwHMroQEzT7yrAg==,iv:EW0W7novbKG6zTefkbbMdexrYYUNy0wNXJEgHcvphrs=,tag:lhpKTzA0cwgz4kUv7q9+ww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja1d3NEpaSXNvZ01pKzJz
            ZmNGRXduVXJvVnBYdzBwYzVqNTMwR1dvVFc4CnhGRDY4R0RyZURaTWlwSjBhUndu
            L3N3UjJPM3plS2xiUjF5L0ZyU3U1SFkKLS0tIFF1ejZIQm9GeDFObDFkNlQ3T3h1
            NTZHZ0I5cG5vdWdhMmt5akM3dE1rVGMKX4cZNfLWHhqXH/pAkl1OBmaY6QY0+SnB
            49k31arl8PZTKUlzBQ7TFZlb/zaElaEAtjn1Sp6FIeGD+NpefbBhww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T01:07:52Z"
    mac: ENC[AES256_GCM,data:R/6kq578zaF2qqphCjXKvZzWmyGe2JNXhRwdrK4uU5FyW43haMfIRSobeykFBLRz4Vb4hzk4fltE5Gk9MxHbPBKVPl1pLiHYZAjZdu7sOkKrbM9ZK28yXPw5xZ1yYBZwiFXUUGfFY8SZbiE11mrzun5IOSBbFdvTLfiBgo5TAyM=,iv:gW+SAyh60X59rfKcSNTeDZzHO0AVLbxv66eseLXLKPA=,tag:1n7haT9smewfMU8S4IDOsQ==,type:str]
    version: 3.13.3
