---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pihole
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pihole
  policy:
    semver:
      range: 2022.7.x
