---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  suspend: false
  releaseName: pihole
  chart:
    spec:
      interval: 30m
      chart: pihole
      version: "0.1.x"
      sourceRef:
        kind: HelmRepository
        name: permalost
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/permalost/pihole-helm/blob/main/charts/pihole/values.yaml
