apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  type: ClusterIP
  selector:
    app: pihole
  internalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  labels:
    app: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  externalTrafficPolicy: Local
  ports:
    - name: dns
      port: 53
      protocol: UDP
