apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:D6iKMe5s359/Lua3pzYxXDkRGyjrQXliP8koN1S4gqcw8cdbPDdGmZXi3e2m19YOAmGrzsWGiNlzyMJab61pRg==,iv:zLUwqJbRZ1niBx8YfXObrTDJRZRy24fW/KojNiOO5lE=,tag:9Tw0KjNkEagie5qHM27nHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NUJRYmVlVmFLR0phV2F1
            Rm1OYmFkRzNGczhnTmo2WlFKaTZFTnA0VENzCk8rY1BPUjFDZmVncGljOWhqUzBG
            UFgwRWdsREp3TXpnQW5hVkhDYy9FbWMKLS0tIGhVQnNDSjdUQTFuYU51VXF0NlFl
            clZQeTZwRXBqSXV4VmpIbldoQ0N0SzQKG1W+Vjgp1AQLudU5gc0dWo7z1NP1s49e
            kOTqTGnB0292ee51+VikCFbuayrX4VMAnpBuF6qTdKFgG8Ws1W+TJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T03:18:36Z"
    mac: ENC[AES256_GCM,data:PM0Iarit212IBen4WdKZryC6HyZRMAnKusg6vW2iSSGfhfTC2cnWqz4gyfDkTTEpisEAp28IvfkxeRugTx2hVVeFs/nwv++3akg4ynHmEXcq5Z2NpGSisT3bAE4SrOlV4IJrxDLyr3gIOEDHCciq47yIm0b0NKAYrMKjYVgIvDc=,iv:RdjTQXkiqAd8/YyyJj0bm3KwESveZh5F5LhYEQFm5eI=,tag:T2rwSo1CrLtfsP4sZpQuZQ==,type:str]
    version: 3.13.3
