apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:dOOnp6bJ1geZWhfCBs0vEcDfz7Jid0h2MmSdtEU961GTL8FG/NRvCk8RfB0lm1LpmQy+dpcQVECcWnQqFMlKqg==,iv:d8+eFeC1nqQxB8mgBf4HhiGBwtDpeLjgKdsjr1wdJSI=,tag:QLqx3Xzeodq5zCA25PjpEw==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:RPN1buU=,iv:Us0nlIcyhPaKANTlXTnzzqx51jnaFdFBAjGVULx4Cyc=,tag:A5x+QCugFHXNhPEQwZjs9A==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:3AFrR43fTukt/LJihBgY7jl11gk30czA5sP+Ag3UvhM=,iv:055Lx++HFE1PQJnVZeLyCJMKFaB8X4i4/fyp3DUNL84=,tag:hn4fVnvjwXLrFguWlrbisQ==,type:str]
    HASS_TOKEN: ENC[AES256_GCM,data:4EUIr2HUlo+TINoZXoGwLyhQgx9elestia1EIPlBitgjwibh4AnQ/iq235bKEy7mlym2mLeegbn/SIxyGHZAkHEn+A4RVuHAJe8nHtnjOgU7c5DRZa3EG5Fyc/l55OZMCVGy4rPxBkyjoOFjRYC+Qtk/pJmifCPOO5l7BW6eNqYSgud69qvKIKfLHI+2XmRWTAQ9o9FfeOZGDrtQFfmTI3Iz5TFsvdDhVP7Mni27YV6td1Ae8Lu4,iv:EO1y8ZCcdfpZQ+36tfaMxOqwU5gVLtx5clNSdFhDF5g=,tag:6sA5MLV3o+BS0cW32oJOiQ==,type:str]
    #ENC[AES256_GCM,data:tI2NzPqUJ+qJaQyrA4ZEcx6prRKyq2MJMZOMjqATWw1V52Ftg6ZQwzIkX/2YPmWWNJyrZ6oR1KGyBgwjoSz22+b+,iv:43qmfIWZ24usqgPRksZoF/Cx7D6bCZqfeVq5mfJyHhs=,tag:Ds/DuvwhNYc3YKLnMRFFAQ==,type:comment]
    #ENC[AES256_GCM,data:UZALroyzw46tZeAN/pMkcJjACMoDwzmH4n/KdUs1QveiizdwlLoXgHO1IOKRKObpVPlKsY/4UnTT2OkTuz2wRZe7AKE=,iv:IDWOK4u3lxfaWI0tkTgi0KcisKZfk+JMBvvxwZmBEoI=,tag:X6In96NrhxoelXYKnj5fZg==,type:comment]
    #ENC[AES256_GCM,data:en5v9BUKiXWUxExlKh3K/zak5AesLWEUVRqDTg9ExJ8SGABT0+7tkdtdHH7WpqykAs7dB1jKNSig26cgfOMfW90WCe5n,iv:hUMasBOnOlCtQ594r9IYGOoc6RQjzLyB4pELjo6CvCg=,tag:FJGKDhJLU3AZEr8hQlfaaA==,type:comment]
    HOMEBOX_API_KEY: ENC[AES256_GCM,data:26CGmTxAI3Nx+vI/3IJIKhBK6JIGmGiZMJC5cxAHyvsJg0mi8u9XnOup/X/egg==,iv:Xtn37VYabxCZse73aKqQxCwcWxHG4Itqhp3okqON9Xw=,tag:Xh9L7LcFwOGLc5rlFHQ2/w==,type:str]
    UNIFI_USER: ENC[AES256_GCM,data:ocOOnkmN,iv:9HZ3r1Fhgs7nfCUheeRw3v7g4HWgvdZAQ+F/qDx1NiE=,tag:lSJb4CSUiYO+I4PMsGYykA==,type:str]
    UNIFI_PASSWORD: ENC[AES256_GCM,data:hfngQqgMshqt3wnTRNM=,iv:kPxtZUwvRZGrwvSTGZQaTq3hXmTAA5maS+mgfg8P9DM=,tag:LAIS2gmbWvrrYSd3Uek9+w==,type:str]
    #ENC[AES256_GCM,data:KUqJdPvAm1rLXH9LzsE07X1i0NZuWdE3MeNEyce/z8yX3Qm/DaF1XlpIbrV1cGyhDv0lBcI9NlkBkYB9WrDt,iv:6WOfOlSyQvI5iFPUJHwOCfyRYQinWUhVLnQqgEO/lZE=,tag:4QvUNByy9VfeOr3rvfVP0A==,type:comment]
    #ENC[AES256_GCM,data:20xaJwyxXo12n1Mk+gzSx0UutTKWsv14F6Fy9TPN2JYboROL4VUncY9M7VJCm3SN++K4WSVrshnuhtsIWAa09OOU04s=,iv:jvT1TDj0PmghtmAhLD0jRSq/iRxWz7XaS0v7mom9qDo=,tag:tjamVchPNmfj2apIgtmgHQ==,type:comment]
    #ENC[AES256_GCM,data:8zb0NPXF0u9cLa+PXXukzs+ZfzgLMUCQRI1CW0Bkaq5T3RiL3q5Lqcs54C5TXJE/Z0qR4UiUznzHpOlwlLCxxjByOerdtyDAQ84=,iv:WYyAPpgflBh6hC4HeHeA8M4LON8KC9q3laH2Z/GEGfs=,tag:B6r1Q0AznY9clRGomOw7Gg==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:TUqFY+86jabgjFEB/rahrmG5PUhP7CVzNT33j2GLsLfOhc7+QQi932yJKEPoMA==,iv:SHLpKQ4KTf/p2Y7u5FUBaKh4+YNzc931ayvavuO5UWc=,tag:yo30jGK/yeEh4Q3izsYX8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QzYxZVFLeUgzT0h5YXJW
            Qk94Qk1PSVhIdUJ2Z0hpZWpmQmxHbmpIcndrCklmRWw1R3I2eHpiRjNrZkJlb2lt
            Wko2TEFYZlpMZUZRQlZiOWVQUDdOQk0KLS0tIE9KSXBhR0o3V0xybzhlYWdBc2JF
            ckNuOW4rbWh3MnZyZzdyWllWdjlONkkKY1GiPStgigpCEgH3Yhf5su0UxSG1aLfM
            s//Vq3NMR5aJ5K/hLFeC/TbhfkvmxVtavNxCZ/UXq2ZT4LjpOvncvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T00:50:37Z"
    mac: ENC[AES256_GCM,data:Fg6wCTPBifIpov6PhKrHSDuDytuYBTwn3Xa84MIbigDLjntSgzlmtEMTAiUj9OIbA9z4ZNGmD+EyjnQrt0Y4XBnBbgz3TtgqQLKFZgxHZT/6+hJNuyT4Tm5dSMtWOpMdcLgp/64RDCVQwoOgvtme+66Jyrle1wsrQ5uCRVKNj6M=,iv:NbFO7YS8MJ2MFm15GA/yU3QGOikDHlnl1hqQWgTgCUM=,tag:J3CLXCfe5+K7UiIF2dwOIw==,type:str]
    version: 3.13.3
