apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: template-ns

commonLabels:
  app: template
  app.kubernetes.io/name: template
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: dev-team

resources:
  # - configMap.yaml
  - ../template/deploy.yaml
  - ../template/ingress.yaml
  - ../template/pvc.yaml
  - ../template/service.yaml
