apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-home

commonLabels:
  app: home-assistant
  app.kubernetes.io/name: home-assistant
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: dev-team

resources:
  - configMap.yaml
  - namespace.yaml
  - release.yaml
  - repository.yaml
  - ingress.yaml

patches:
  - target:
      kind: Namespace
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: default
        annotations:
          linkerd.io/inject: enabled
