apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics

labels:
  - pairs:
      toolkit.fluxcd.io/tenant: ops-team

resources:
  - namespace.yaml
  - ../../base
  - ../../../loki/base
  - ../../../victoria-metrics/base

patches:
  - target:
      kind: Namespace
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: default
        annotations:
          linkerd.io/inject: enabled
