apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-settings
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 30s
  timeout: 1m30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/clusters/home/settings
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
