---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: backend
  namespace: flux-system
spec:
  dependsOn:
    - name: flagger
    - name: nginx
    - name: democratic-csi
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/backend
  decryption:
    provider: sops
    secretRef:
      name: sops-age
