apiVersion: v1
kind: ConfigMap
metadata:
    name: zigbee2mqtt-settings
    namespace: home-assistant
    labels:
        app.kubernetes.io/name: zigbee2mqtt
data:
    configuration.yaml: ENC[AES256_GCM,data:rEQxORxfjBBi0lwhMtTndNaAgVvtG6P2FDVhWNel1b1IaUfhqidzZtYNpIrlF+q4OoxRbY/Y0iN0O1wGPS7Ugf+IB6U3wK41bMmPNX5jEL7Mc7wfg3cexNI/jZZa0xGD6s1VtSz9bcYAZf40oTlXGrMqpk/AzZJMT/LIsVMMFOT5cmkcy6oNOf6SbVykOH2cgynIbhVM7HqvbgWMieIYSyn0TTKSWKG0TcvMCjfROUdHJ0FcQbjdTI31LznXJ2sskSVgLmA3xV69GgdVpjIpMER4Zd84cFx/BnDU266TqE1idg77XL0kkamXlUIs4fKUkschPWZnTX5YvtxO3wFzGq/ms4n+zx4saYnX3qGFHBNZmY8H5itP5VcKoK0cNth5Ae6Gd3lV9/UK5L3NdUMz046D+inwC/QP5Nkngy7XmVUa05NiwhMDVKKX4CUpb7bbO9jiOMzirhVhM2sLVHqP2xCN2hhCZCyhkE1AMozVZ2YClpdxPJSpr7OwjPLZBGODRwc30LTTBiCsBQOzIShB+NzDAN6Fq2tGCs9Bu9UgjC3sOwZVks7kVQLIUnykyM9ktVynYs8rq5hTbQ/caN88T+uuptVzK3EIm8CPXve4zSvy0QsHPEPqmbPg5pSKdvBmrA==,iv:Y810KNljwseDCKbXwl+/jHnzerL8tKWW6IY/6C8LAYQ=,tag:ZNOp4SHH8xGH/MTmJZSPdg==,type:str]
    devices.yaml: ""
    groups.yaml: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMGYxa0RESG80bFd3Nmor
            WEhvbjhVQ25rZXFHV1JXT1M4NEZyTk1ITmpZClZ0dTA0WURJZi90SWlZRThML3p6
            eW85bHNZR3piY2V4Vkk0THU0S3EyZFUKLS0tIGlicDR0bzY0RVViZVlnNnd0RVRZ
            dUx3SXhpYUxOSEZ4TWVFSlV2YXpYQ1UK02Al1Yqhv8VzHeToFgN6hE7EG9gRL/M8
            uRnT5lFVVuMF/qP4fSLIhkZsW4SiMVaJ6h+7SuUfATydRrk4FeeJkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T22:30:25Z"
    mac: ENC[AES256_GCM,data:2XhHZBnKcFi3gzLdNJ4432FnkUMRBSL1jBnwZJKFvah/B2RNj6ShwnBUnFpQ/VYavjwCYQcF8vJWIyUysMgJQ6mChndXsZ5YwMPNguRChmSuLZkn7TFxCm/H3qioitNaowK8WU34EfnNORRCqcqSMJSNsIoOqbbyl6kp3Sdh6T0=,iv:PlVVO8oiSFkMLy2x81kofkaIiYvQJipj7YaLxJcvo2c=,tag:hnGVcMrgGO6c3SYSBK2tug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
