apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: zigbee2mqtt
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: zigbee2mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zigbee2mqtt
      annotations:
        linkerd.io/inject: disabled
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: zigbee2mqtt
          image: "koenkk/zigbee2mqtt:1.38.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/Boise
            - name: ZIGBEE2MQTT_DATA
              value: /data
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: writable-config
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      initContainers:
        - name: init-config
          image: busybox
          command:
            [
              "sh",
              "-c",
              'if [ -z "$(ls -A /writable-config)" ]; then cp -r /config/* /writable-config/ && chmod -R +w /writable-config/; fi',
            ]
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: writable-config
              mountPath: /writable-config
      volumes:
        - name: config-volume
          configMap:
            name: zigbee2mqtt-settings
        - name: writable-config
          emptyDir: {}
