---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-assistant
spec:
  suspend: false
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: zigbee2mqtt-helm-chart-values
      valuesKey: values.yaml
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.30.4
    env:
      ZIGBEE2MQTT_DATA: /data
    service:
      main:
        ports:
          http:
            port: 8080
          metrics:
            enabled: true
            port: 9000
    volumeClaimTemplates:
      - name: data
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 1Gi
