---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-assistant
spec:
  suspend: false
  interval: 5m
  chart:
    spec:
      chart: zigbee2mqtt
      version: "6.2.1"
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: zigbee2mqtt-helm-chart-values
      valuesKey: values.yaml
