apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvidia-device-plugin
resources:
  - namespace.yaml
  - runtimeclass.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
- name: nvidia-device-plugin-helm-chart-values
  files:
  - values.yaml

configurations:
  - kustomizeconfig.yaml
