apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: webapp
          image: my-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 500Mi
