repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
  - repo: https://github.com/onedr0p/sops-pre-commit
    rev: v2.1.0
    hooks:
      - id: forbid-secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.31.0
    hooks:
      - args:
          - --config-file
          - .yamllint.yaml
        id: yamllint
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.21
    hooks:
      - id: terraform-fmt
