# https://taskfile.dev

version: "3"

vars:
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes"
  PROVISION_DIR: "{{.ROOT_DIR}}/provision"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  TERRAFORM_DIR: "{{.ROOT_DIR}}/terraform"
  INFRA_DIR: "{{.KUBERNETES_DIR}}/infrastructure"
  LINKERD_DIR: "{{.INFRA_DIR}}/linkerd"

dotenv: [".config.env"]

env:
  KUBECONFIG: ./kubeconfig
  SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt

includes:
  gen: .taskfiles/General/Tasks.yml
  flux: .taskfiles/Flux/Tasks.yml
  k3sup: .taskfiles/K3sup/Tasks.yml
  link: .taskfiles/Linkerd/Tasks.yml

tasks:
  default:
    silent: true
    cmds: ["task -l"]
