apiVersion: v1
kind: ConfigMap
metadata:
    name: victoria-config
data:
    prometheus.yml: ENC[AES256_GCM,data:ozF+Kq/U1G9anpjnEOsQVpb54xPaagmuGv1U2sJPPw5HMcgndrtah0HDJA5bmdib5kIFgyDZFELDVYZ9LaCO5jQyxXvJJi9bjwlDO/v8AIGMjAd+FWg0FYsaXXgC7IyE/+I3ufp8oAxjb+S5k/dcG4q3h3e2r39O+ebyX2/ZsjPIp6gkAI3JcYjsBs07nKREzhCmLfp0NKmZ5D9aVhY5/p+O41XnJtN8Lqxw14I2M4lil3U+Qjut/bjxKGp+wWWTBu02C/TTLPLZIi+izxIxFFZyCj/r18fiLowaQNdOl5z9FKDQn9JWgMcS6iQ6l27hCAUYpHRt7JV/oWByWormjNXFLpeQLRngMuVP6kbk1XHfQJXCZtMrFTiSUICyXswh+ZgTRlLpYI3OMBhS47NxDN/vA1S/l3TW9JciY4QJL0TzjqIPqWojCQUGBV3r1IGzpsY/BI36gdOlfmOsIHRzg7//be6P95Z6tfKQeaJsVVQsixDMM4U7FfeqicV6/ej/KH79bxyEFSjiR3RMaEaV1Bjvrt7GjOVFAqk=,iv:nFD8RRXs2cJkDk+QcLmDAjYea+ssQSvF/EqDjtLXNNM=,tag:eXzpL99pDpzPtHvhziPtCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMGYxa0RESG80bFd3Nmor
            WEhvbjhVQ25rZXFHV1JXT1M4NEZyTk1ITmpZClZ0dTA0WURJZi90SWlZRThML3p6
            eW85bHNZR3piY2V4Vkk0THU0S3EyZFUKLS0tIGlicDR0bzY0RVViZVlnNnd0RVRZ
            dUx3SXhpYUxOSEZ4TWVFSlV2YXpYQ1UK02Al1Yqhv8VzHeToFgN6hE7EG9gRL/M8
            uRnT5lFVVuMF/qP4fSLIhkZsW4SiMVaJ6h+7SuUfATydRrk4FeeJkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T19:03:44Z"
    mac: ENC[AES256_GCM,data:149c6cxn7v8m06MvJyF3H3+6mZVnUWmMcJvbYfhjcWJt2hfmWc9O73GiIdLKehbdt8epe3TaGpYvQx1EuEELz2XWxrw9xqynpWFa20XTrNVX0RU2XeapdXA2amX69goXRZXluRUWEOPFW5izE2UGAa+60oP1mmKmVUIKhsuc6LE=,iv:3usJpqs6CO7y5E8TFT7AlfOjLjdPcNQ7GD2WlIu/gC4=,tag:jQIsZSaXC1sorb8wVZy2kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
