apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: victoria-metrics
  app.kubernetes.io/name: victoria-metrics

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configMap.yaml
