apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:GSKOu69KcNksLTIbq9kuV91zpEWDHKQre1+Jd1EQPy6xLx3HaKGgcffmdXRmu2BQVBDkdD7yUxqa1pcW0o5KiQ==,iv:Hj5Su/OkflEaCCIQtwFFmjzjLaXTy7g2EA/WDTMJNO4=,tag:vpXI/joTNBPtsXaR+R+ZQA==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:U06owUY=,iv:rjTV9cREuPQpiFL1wtnOn5wi5rXWer4BgevCjBK3oOQ=,tag:mPy4IWKS8fU18yiE97HlMg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:CpEBYrEAqgbpYMrpQAYCycvc+LfHGqUogaJAvKWxdqo=,iv:k3+AKZGVbS7ms/kPAnCJQ/jR6+y1e5C6LMxz5RbRhIw=,tag:MCVETkpEP6UE9zwkcsSJcw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeVdEYy9VeElvOWFIL3dE
            ZVI1ZGpkMmw0ZE9TTHNUVGRDQkVjbVRuaDBJCnozei9RYkU5K2ZPZitJZ0RiNU00
            Q1dlNWtuMmdNWW5MVHVsOUpZMSs1bHcKLS0tIDhiTGQ1VFJDOG54Znd2Sm8zNjZz
            MGo4WDhCMmN0NXUxQWlNSER2RENwQzQK5Rz3ZQiPdwWjISTUE+cRm0ffdqAWVR+O
            lkuzZonrK7sH6I+OhCEQWkhCM8UB6R7ccYvEKy/UX0gmh/SEloBOow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T13:49:01Z"
    mac: ENC[AES256_GCM,data:BgXWDE8btgwlmPDFxwSwIEmg7lJaRGDpgs5M9sBzVVT2kXU1hlAfeHZbQWROiIz7V6jo5X18/hq+bh3qMz//S38kaFhZKnlZr1NM5S9btlpnjw88zl8twrqyzVxY2OpUHkNGbWBs0ijuMw3NqSi+8Bo13Yq6II6XjLCS4upLdh4=,iv:Gm/W/Ckxuc1ggnzQ6pbgWFFZkAI/jUxdicyeQbcwc5o=,tag:+8VgjIYKPyNP5omATrENTQ==,type:str]
    version: 3.13.3
