---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nginx
      interval: 12h
  values:
    controller:
      podAnnotations:
        linkerd.io/inject: enabled
        app.kubernetes.io/managed-by: Helm
        meta.helm.sh/release-name: nginx
        meta.helm.sh/release-namespace: nginx
      setAsDefaultIngress: true
    metrics:
      port: 10254
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
