---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nginx
      interval: 12h
  values:
    controller:
      hsts: false
      # podAnnotations:
      #   linkerd.io/inject: enabled
      ingressClassByName: true
      setAsDefaultIngress: true
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
