apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:7SvloGSgFQ6wiY0itw3u9CUCS2wGuoW2zsM+ecP5B+IuZYYqW26PLQ==,iv:PB/J/B8t1/OhO5waG4gBUekhvubopazpcPzF7KyNXYA=,tag:CXKhRFu4riK4ySvytJ+3qQ==,type:str]
    email: ENC[AES256_GCM,data:LbWtn+iqGr8gzIciWR98g4CnLsD+QJduzGlrzXUsZy3WnQpOBK8OtJs=,iv:p1gxPWF1i2rPghwszaNPdIIV3TtKVhtFf2olzM/EOQM=,tag:RPrkrg5YojbtKbvaLgtSuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSkhKT3NCRm5UNTE0dzEy
            S0E5SVBpQU9xSzlsd29jRXlGNnJJNzQzU0JvCnlZMkdvVzg2d3RSdC9keG43Tkgr
            RDdYQUFsd0Z4ekZ0eWw3N2xlLzVZeDQKLS0tIEdGMTNLdHltcTVOMlllTU80WHJ2
            ZkdGbFFSQnF2RERnZm1QdWhrRnkvU2sKFaO1Kc7fe/yPg3AfD8TTuGKFVK2jj3Je
            hAZEsqh1BwWMLKobEO840YDwAuMlWKoLEGhU9b7Is1NkMoiERBEmaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-21T02:18:47Z"
    mac: ENC[AES256_GCM,data:lS7AV6T+yMEgkF5VrFGmbIlIXWWSOGNX/Ni7aHfGStUk7PkPo3W87AjUTTrUlxPNF2/PRyCFf3tXeb6LC2DFlPnCnF3KeSvDhnaxjk/fTZZsvYa7cznfhFSyxluRKdzn1B27cKzMkh/CsQT538V49/LTg84q+uzYfzYGFDRKAzw=,iv:li0o0ba1sy/P4S5L/Z8kzSV1fzzOBH1KsMGzexxThgY=,tag:tNIqgeKYdioKzq8KULy33w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
