apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../webapp/base
- secret.yaml
- configMap.yaml
- loadBalancer.yaml

components:
- ../webapp/components/ingress

namespace: pihole2
namePrefix: pihole-

labels:
- includeSelectors: true
  pairs:
    app: pihole
    app.kubernetes.io/name: pihole

images:
- name: my-app
  newName: pihole/pihole
  newTag: 2025.08.0

patches:
- target:
    kind: Deployment
    name: deploy
  path: patches/deploy-add-env.yaml
- target:
    kind: Deployment
    name: deploy
  path: patches/deploy-add-volumes.yaml
- target:
    kind: Deployment
    name: deploy
  path: patches/deploy-update-ports.yaml
- target:
    kind: Service
    name: svc
  path: patches/svc-update-ports.yaml

configMapGenerator:
  - name: env
    envs:
      - env
