apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../webapp/base
- secret.yaml
- configMap.yaml
- loadbalancer.yaml

components:
- ../webapp/components/ingress

namespace: pihole2
namePrefix: pihole-

labels:
- includeSelectors: true
  pairs:
    app: pihole
    app.kubernetes.io/name: pihole

images:
- name: my-app
  newName: pihole/pihole
  newTag: 2025.08.0

patches:
- path: name-replacement.yaml
  target:
    kind: Deployment
    name: deploy
- path: add-env.yaml
  target: 
    kind: Deployment
    name: deploy
- path: add-ports.yaml
  target: 
    kind: Deployment
    name: deploy
- path: add-volumes.yaml
  target: 
    kind: Deployment
    name: deploy
- path: update-http-ports.yaml
  target:
    kind: Deployment
    name: deploy
- path: update-service-ports.yaml
  target:
    kind: Service
    name: svc

configMapGenerator:
  - name: env
    envs:
      - environment
