apiVersion: v1
kind: Service
metadata:
  name: udp
  labels:
    app: pihole
  annotations:
    metallb.io/allow-shared-ip: "pihole-dns"
spec:
  type: LoadBalancer
  loadBalancerIP: ${externalDnsIp}
  selector:
    app: pihole
  externalTrafficPolicy: Local
  ports:
    - name: dnsudp
      port: 53
      protocol: UDP
      targetPort: 53
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: tcp
#   labels:
#     app: pihole
#   annotations:
#     metallb.io/allow-shared-ip: "pihole-dns"
# spec:
#   type: LoadBalancer
#   loadBalancerIP: ${externalDnsIp}
#   selector:
#     app: pihole
#   externalTrafficPolicy: Local
#   ports:
#     - name: dnstcp
#       port: 53
#       protocol: TCP
#       targetPort: 53
