apiVersion: v1
kind: Service
metadata:
  name: dns
  labels:
    app: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  externalTrafficPolicy: Local
  ports:
    - name: dns
      port: 53
      protocol: UDP
