apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: loki
  app.kubernetes.io/name: loki

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configMap.yaml
