apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes-hearth
resources:
  - repository.yaml
  - release.yaml

configMapGenerator:
- name: hermes-k8s-mcp-helm-chart-values
  files:
  - values.yaml

configurations:
  - kustomizeconfig.yaml
