apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    placeholder: ENC[AES256_GCM,data:ga++pxdW4soL7Q==,iv:+3nE7yXHYLdzJPv2C8FCyuKysrSQk+sk/0L+Wb09V9w=,tag:7vTkNcE8zMU8Ue26dBJ7Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NEE2Vld3MUd5OElkVHR4
            a01OdThTUVpDeXI2cEhueEhpVG5LL0tISFVrClgwSWdPazFmNmdTS1pKSmZsa0Nx
            N0RFbHVraDRVOVVvellDdmNKMU1ibm8KLS0tIC96cWxrRjNmQjd0TkVjRmpGVmRG
            SEF4M0xEZmRsTWRmTjBOZUxYdk0wdXcKcIJU8NsPre80lK6ZbIDbzFEKstnLEumf
            4dEXI4jEWNzKL//mbiwNtfmVCnzRxwcYP7hJh2zwzMCIEbgC4ygVfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T19:53:15Z"
    mac: ENC[AES256_GCM,data:rJ2I3f6yEcAKGG5SNFDd+mvOBYAjt1nDbIBf2kObrgDUowv3U6N7gy9bWo6oc8awfAbmHx1LbNZpHx56+fvkSLuBP78+6yO8ZSJLs1p6CvcrFo8Ye/92UMH/nqua6GQpNM3y1YZwYYQ+PFm8Xq1xILCbgGYBGe5ygwzgtOkVROk=,iv:SdO9iJ7WfQ9KP5w+bHMRyYV8bgKG4U6fYvXSCc6FLew=,tag:9iv6++ak7AsgPbZGb0uGUw==,type:str]
    version: 3.13.0
