apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

commonLabels:
  app: ollama
  app.kubernetes.io/name: ollama
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: dev-team

resources:
  # - configMap.yaml
  - deploy.yaml
  - ingress.yaml
  # - pvc.yaml
  - service.yaml
