apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:XjDayaNnrH/dGytAad7DgZWzI2KbeJMw7KM+DgKGYrBQlazJh9430g53Jd/qQvZSXgec3E77BZLPOan+iB4fbQ==,iv:++EbrXihFxU4GzSigatVHkTgno4j9kSXodS+m8h3PyM=,tag:RKfmfNdXzZaaOhqK123i3A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T0ZiMXpNOTZGWWYrZEVU
            bWhyblVzdEp6cU5FdWJhTmhtNTNQQXNhbGhJCkZKOHgxV2F3d3FLcGVobEFrUlhZ
            dXF4QW9wSHpsaVZYdEVrNUZpN3d6Rk0KLS0tIHZPV1pzbEdXM2p3Q2xkUDF1SkxM
            ditHaXIvSUJMTkNMVTNjR1ZWWW5EaDAKRTcuTg9FykDvs9acLbkvVk9kkSklEs2T
            paMPzq1MuBGmooQqSUdjf6fQAOhKhzHLY2c7qT8XBEWYkkyo4Qhxog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T03:18:36Z"
    mac: ENC[AES256_GCM,data:yooXVLvAWhL45hTCxBmoZLAYrgT4AuCwxi85iJR8WDUrT040y+5ByIcKLgmSxBY9je66SrOyqAui+nzN1FjvGE8Kt2+Ms+x9jTdzR1N7sCbC7CVf4eWnAy8lY8XX8GQyeAaBc0jdS1FjcBOvtrT1qxXTs5EORc6v1oYmGZoxt+c=,iv:KtM7R+5Fl1s0HrcEUsXp6cE7OtC+AaIevWfQdHXV8EE=,tag:XH+RsHfkAB9f0WBPbpuM5g==,type:str]
    version: 3.13.3
