apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  suspend: true
  interval: 10m
  retryInterval: 30s
  timeout: 3m30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/democratic-csi
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings
