---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  suspend: false
  dependsOn:
    - name: flagger
    - name: nginx
    - name: democratic-csi
    - name: zigbee2mqtt
  interval: 10m
  retryInterval: 30s
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/home-automation/home-assistant
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
