apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  dependsOn:
    - name: nginx
    - name: cert-manager
  interval: 5m
  retryInterval: 30s
  path: ./kubernetes/apps/metrics/loki
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
