---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ollama
  namespace: flux-system
spec:
  suspend: false
  dependsOn:
    # - name: flagger
    - name: nginx
  interval: 10m
  retryInterval: 30s
  timeout: 15m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/ai/ollama
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
