apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: plans
  namespace: flux-system
spec:
  suspend: false
  interval: 10m
  retryInterval: 30s
  timeout: 3m30s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/plans
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
