apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:main-latest # it is recommended to fix a version generally
          ports:
            - name: http
              containerPort: 4000
          imagePullPolicy: Always
          env:
            - name: AZURE_API_KEY
              value: "d6f****"
            - name: AZURE_API_BASE
              value: "https://openai"
            - name: LITELLM_MASTER_KEY
              value: "sk-1234"
            - name: DATABASE_URL
              value: "postgresql://ishaan*********"
          args:
            - "--config"
            - "/app/proxy_config.yaml" # Update the path to mount the config file
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /app/proxy_server_config.yaml
          #     subPath: config.yaml
          envFrom:
            - secretRef:
                name: litellm-secrets
          resources:
            limits:
              cpu: 100m
              memory: 8Gi
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: litellm-config-file
