apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

commonLabels:
  app: litellm
  app.kubernetes.io/name: litellm
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: dev-team

resources:
  - secret.yaml
  - configMap.yaml
  - deploy.yaml
  - ingress.yaml
  - service.yaml
