---
version: "3"

tasks:
  verify:
    desc: Verify flux meets the prerequisites
    cmds:
      - flux check --pre

  install:
    desc: Install Flux into your cluster
    vars:
      GITHUB_USER: '{{.GITHUB_USER | default "permalost"}}'
      GITHUB_REPO: '{{.GITHUB_REPO | default "home-lab-ops"}}'
      GITHUB_PATH: '{{.GITHUB_PATH | default "./kubernetes/clusters/home"}}'
    cmds:
      - flux bootstrap github --owner={{.GITHUB_USER}} --repository={{.GITHUB_REPO}} --branch=main --path={{.GITHUB_PATH}} --personal

  sops-setup:
    desc: Add Flux sops secret into your cluster
    cmds:
      - cat {{.SOPS_AGE_KEY_FILE}} | kubectl -n flux-system create secret generic sops-age --from-file=age.agekey=/dev/stdin
    preconditions:
      - sh: test -f {{.SOPS_AGE_KEY_FILE}}
        msg: |
          Age key file is not found. Did you forget to create it?
    vars:
      SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt

  sops-create:
    desc: Creates sops for use in your cluster
    cmds:
      - age-keygen -o age.agekey
      - mv age.agekey ~/.config/sops/age/keys.txt
    status:
      - test -f ~/.config/sops/age/keys.txt

  reconcile:
    desc: Force update Flux to pull in changes from your Git repository
    cmds:
      - flux reconcile -n flux-system source git flux-system
      - flux reconcile -n flux-system kustomization flux-system

  hr-restart:
    desc: Restart all failed Helm Releases
    cmds:
      - kubectl get hr --all-namespaces | grep False | awk '{print $2, $1}' | xargs -l bash -c 'flux suspend hr $0 -n $1'
      - kubectl get hr --all-namespaces | grep False | awk '{print $2, $1}' | xargs -l bash -c 'flux resume hr $0 -n $1'
