apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hermes-profiles
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: hermes-profiles-deploy-key
  url: ssh://git@github.com/permalost/hermes-profiles
