apiVersion: v1
kind: Secret
metadata:
    name: hermes-profiles-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0jf4VfN9LaqLXiilXVRC2zKDn6Z0UC/64Wr3C13rNMmrhPNRcM+cG5dUPHLIxK6dZFPdiDQfm9k1+TN4GS+qS8xOImAJvKmbnrjn673gJJTYWt1z9NspzsXhMo2QS4xkkyAXzGQyxo78l5pb+LjHtoswyyMR8g6QTeRAHzSb0bGuogyh+DZNFONcjyvvYaTu7pamruHzpidcRTqrAo+ahCdPS083mg9ynl3ydLfWrK7l8VNPs7kyluEnYsiLitykyATblSZrX6tkYBS0kaLs9K4vkYM7fPtrv1hqp6d6pwXtdcY8XXt1ZK7zHXzTAhVV9FoVlZlb0+7Xt0/QUchLHN91jyMbQnwByOlFRZ03iGi7dR7QLfBDmvixuSzRSJ5oK+G+j5m2S5Q+OSHHh8MwftrFY+f25yQgxxBVJVHwGtgGRsw9JGwPrQn/gL2zqMILydeH4IE7KVfQzF+jkcWnWkJu4Gj+DoAiMLnC0ym+1KmxdXqdk6pfy3CwVKp++7RF13xC1WaZlTxuxwmMMQnuGVaFH1KnoFCV92O4fOqoi2i5cBm+RZ1sqsMXCOBOpRK5,iv:Ce1creFReTt/z0I3+XVuERLG4tR1LScpVzFtL9SnU3E=,tag:nzR9q+iYfkJXIYBdSC/USQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:1eIoKzXQQ+bonQDpwGcwcM/HoxF0UAVPQbwBBJu/p+EadiS5WAabFTgN018G7vAXmVQx4tk5HnmsDJR5w59AS7CBXpQ4mhwxsxRBLa23+3iU5D5lmnbOmvyBWviQN5Qv87h8UN8ahTSfU4SPLAhqf0Z4Rk2BTNLSJZ+VyA==,iv:bajYB18BelXxN2vS5ksHW9QsvW/qpLqol6mX04S0+vQ=,tag:vWAybSO70eKqpS7jasRRjA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTWpRUUdZcHNuUjFuT1VI
            SC8zNHNzVk9qbFBXRkM2TXgwandORWp3M3d3CkJkT3cxaG5wMkFCNDZ1RitCYnUv
            aGdjaE9lWHZ5dWgrTGVJUXljaWZmelUKLS0tIFNwdGNwV1UrWUl2aUxDWWs1Q1N3
            NGR6WGphSGJQS2U1V1IxYVh5bnNJdDgK6fGglJySCdizNWj/orgK+EHkra17SoMQ
            9QckhTXowdZrTmhCcvKfbwmrajq0LS7ms1W6OVXETj6LUGdGWr7uEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T17:17:38Z"
    mac: ENC[AES256_GCM,data:Y6clwDQNXJjXYdYMwmACL/jW0kj7k3H5f7Z29SjJOTVs+2UL+idWdQFlre9rIYu3Jtoe5mUFuC+xJ+9l9mTErsLuaC2Cm2YzBHFGvYyV0SGGOQ7wixK0N0wcRw2qpcJSugr8TC2XPMuDh1/OjVRxwqoQR7fR12+3SnCjeCZSw/8=,iv:zrlXoGjQ7IPedIW8K1GZguOohu8QtT9thFT1IAfzTMY=,tag:XRG4eEY5e2LsSSUuQAxaGQ==,type:str]
    version: 3.13.0
