apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomizeconfig.yaml
resources:
  - linkerd-crds.yaml
  - linkerd-control-plane.yaml
  # - linkerd-viz.yaml
  - linkerd-smi.yaml
  - linkerd-certs.yaml
  - repositories.yaml
  - namespaces.yaml
  - secret.yaml
  - ingress.yaml
