apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 30m
  targetNamespace: linkerd
  dependsOn:
    - name: linkerd-crds
  releaseName: linkerd-control-plane
  chart:
    spec:
      version: "1.x"
      chart: linkerd-control-plane
      sourceRef:
        kind: HelmRepository
        name: linkerd
      interval: 12h
  # https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.crt
      targetPath: identityTrustAnchorsPEM
  values:
    identity:
      issuer:
        scheme: "kubernetes.io/tls"
