apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
    name: linkerd-trust-anchor
    namespace: linkerd
stringData:
    tls.crt: ENC[AES256_GCM,data:HkLh/eNM3nDEyU8Ri5/wnp0Q/SKp4nbd,iv:mi6vMli6kNddioHndmgIZsfB4kIRaPbVcGJny3Ziu50=,tag:+gzhVJHQ8tSpLdKO+PVOAQ==,type:str]
    tls.key: ENC[AES256_GCM,data:3HaPoBwo1PmvfGWNCbehha8fgvgzBoxr,iv:3XGACqHApOpUTWxxi/nyhAjIiK5NmhtdGtkNhLkm/ig=,tag:XvYt+h2MlvqSDVTnZbmtHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQlNtQ3E0VGtCamZ3MHlJ
            NUltZi91anJnWWlaNHJ2N3dLcFdvbVpLem13CjVYdURFWmJMU3ZKaENPR1VDK05i
            K1M2QkxTYnBTdEZDNkFTc1plakhaTTgKLS0tIEwwSlp1VXVsdmkrU0ZVSjNmSy9r
            UkIxZ2hRYmsvamJoNHcwYklmUGFFSmMKhbzKr8u5SzKHQvdzuVTH4rr4c/Bv/RUi
            rcxsfW7qaXGoWed9CCTLCFSNm5t/5etBxYknje/4CTaHpBcVGuJI4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-31T15:04:45Z"
    mac: ENC[AES256_GCM,data:vBmBxu4vaWrcFg1CcwOHfFip/yxUSrFhe39JXdE8TeXaOhXUx6PJGv4tzd3OjLyzfpyPNXMZIxhb9iHilJZHOICePcy8uwBS/YHVz9vL5U4wBeLfc96/3LbBkL4DMs7Z38ltlFBJ8mZxlO0VhEZIytyKaS4o6LWXtwvQ+3ZfvoI=,iv:39NjRlRpkXyNmgOmTCmqQcwaLrMbL8avGvRxL+lj018=,tag:P7bZ+/6MBCv93DoJx+TBtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
