apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - pvc.yaml

patches:
  - target:
      kind: Deployment
      name: deploy
    patch: |-
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: data
            persistentVolumeClaim:
              claimName: data
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - mountPath: /data
            name: data

configurations:
  - nameReference.yaml
