apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

resources:
  - ../../base
  - namespace.yaml
  - loadbalancer.yaml

components:
  - ../../../webapp/components/httproute
