#cloud-config

hostname: na-{{ trunc 4 .MachineID }}
users:
  - name: permalost
    groups:
      - admin
    ssh_authorized_keys:
      - github:permalost

debug: true

install:
  auto: true
  device: auto
  poweroff: false
  reboot: true
  image: "docker:quay.io/kairos/opensuse:leap-15.6-standard-amd64-generic-v3.2.1-k3sv1.31.1-k3s1"
  grub-entry-name: Kairos
  partitions:
    oem:
      size: 60
      fs: ext4
    recovery:
      size: 4096
      fs: ext4
    peristent:
      size: 40960
      fs: ext4
  extra-dirs-rootfs:
    - /mnt/longhorn
    - /data
    - /src
  # bind mounts, can be read and modified, changes persist reboots
  bind_mounts:
    - /mnt/longhorn

upgrade:
  extra-dirs-rootfs:
    - /mnt/longhorn
  reboot: true
  poweroff: false

reset:
  extra-dirs-rootfs:
    - /mnt/longhorn
  reboot: true
  poweroff: false
  # Override the grub entry name
  grub-entry-name: Kairos
  # if set to true it will format persistent partitions ('oem 'and 'persistent')
  reset-persistent: true
  reset-oem: false

k3s:
  enabled: true
  args:
    - --disable=traefik,servicelb
    #  - --flannel-backend=none
    - --write-kubeconfig-mode 0644
#  - --disable-network-policy
#  - --service-cidr 172.23.64.0/18

bundles:
  - targets:
      - run://quay.io/kairos/community-bundles:flux_latest

flux:
  env:
    GITHUB_TOKEN: <REDACTED>
  github:
    owner: permalost
    path: kubernetes/clusters/na
    repository: home-lab-ops

stages:
  network:
    - name: "Setup users"
      authorized_keys:
        kairos:
          - github:permalost
  boot:
    - name: "Set up various kube environment variables"
      environment:
        CONTAINERD_ADDRESS: /run/k3s/containerd/containerd.sock
        CONTAINERD_NAMESPACE: k8s.io
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Add flux-system namespace manifest
      files:
        - path: /var/lib/rancher/k3s/server/manifests/flux-system.yaml
          content: |
            apiVersion: v1
            kind: Namespace
            metadata:
            	name: flux-system

    - name: Create SOPS secret
      files:
        - path: /var/lib/rancher/k3s/server/manifests/sops-secret.yaml
          content: |
            apiVersion: v1
            kind: Secret
            metadata:
            	name: sops-age
            	namespace: flux-system
            type: Opaque
            data:
              age.agekey: <REDACTED>
