apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
spec:
  replicas: 1
  selector:
  template:
    spec:
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.76.0
          ports:
            - containerPort: 8428
              protocol: TCP
              name: http
          args:
            - "-retentionPeriod=1y"
