apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-home

commonLabels:
  app: victoria-metrics
  app.kubernetes.io/name: victoria-metrics
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: ops-team

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

patches:
  - target:
      kind: Namespace
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: metrics
