server:
  retentionPeriod: 14d
  persistentVolume:
    storageClassName: rook-ceph-block
    size: 10Gi
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
