apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: grafana
  app.kubernetes.io/name: grafana

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources/datasource.yml
  - name: grafana-dashboards
    files:
      - dashboards/adventureland.json
