apiVersion: v1
kind: Service
metadata:
  name: dns
  labels:
    app: pihole
  annotations:
    io.cilium/lb-ipam-ips: "10.50.0.231"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: pihole
  ports:
    - name: dnsudp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dnstcp
      port: 53
      protocol: TCP
      targetPort: 53
