apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-base-config
data:
    mosquitto.conf: ENC[AES256_GCM,data:BatVra9RT7bBqqxU2yTltwaGWP5UxfUB/LyeMK99062OcYxuDIHR02idKX52EPQMWMu7QhdGaEAl5Bmx5zjGSag653sV4vT5LYSjK6YkvoNDb9z3Bt6IGf2FHdNY2szFq8vv3prKBoQLk4jpJyaOx7l3GUmJXto3bSXUvOkt+lULOrs+45i6SoA=,iv:JAMiedwjQqfWmB0lWQJF+LSiJEUa6LM9NUE5pfVQ1yQ=,tag:nKZFGlofTIoNUwfu3kyHGw==,type:str]
    password_file: ENC[AES256_GCM,data:X/6IiNcRA0ZpEUisvtQapHngodiasWVub49sJyfXYIQebZQvW35iP/IfTwrI9KaS7+bnwHaUJdSdYkyM1NbOj81ICresQ6gnfsosuh9pZqdupGn/Vn7AG89BlzUbamF2wSQBVMjjMv4tBPrXcHilhXbkbnECu9RQGRI8BAH//3QLXfTpU4E1g8kmT3Xrk+RV4HD6VI6JJfaq742FzVvo7bkg7E9Re2shr5F76yi7jfLWHANRdEThj7RNRcyvhaboYURCnkDDb8gUPe3Vb2pPQdBpXWAmvZ1Nq+Zmcv2YFB+Yv61jLKAVrXzChUU23KK4CaA1/yLCsp3vKk+4T6vh,iv:InqOCVdE0VzTHBgGCeo9lZbEGLs6ajCbNmTlygcCD5E=,tag:gdBxU8qV/g8NY2HITYy15Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaC9nT3ByQ0pFWnFhdm9N
            eG5URWthbjE4T1F3OURkeWxDUUd4TXNNSWw4ClJ3dkt6azhWSFNVTmc2VFlhSDBD
            WjVvL1F1TmVUc042S2xUVDRuTVl1V3cKLS0tIFFwRG9oU09ncFd6TmZnVVRMVmpR
            eTNKZGRWMGlhM3Q1YVVGcXIzOVhTSFUKtP4rQXan76HFYTpnIgZ+/LvTZ5LLRarv
            l7a9qiIclY3R1uLMV2D4vzGSTFXzplTtnkb6Fcxcb1G8MAff0HWExA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T01:03:09Z"
    mac: ENC[AES256_GCM,data:Rp6w4qCimKLhjNKNZQVcHnqVXl7rN+W7MaFWq5n+F5I63lAsDicmNh+nGW5SUdxntuj0/rMn3E6f8kSIKjcdQhwwuD/QX5zy5YYW5FITi0RsGjz+HI+6SE4U0Hozk4sPBCIhAcN1RZdE+BrI/QTzNzUV1M9Ljbecw5ArFSQLJEs=,iv:wkgGn1psRskX5DgKL+BE1/VYy6WDFvwem9hK1EHnR2Y=,tag:/3LKbFrcAbwWrOirYiBltg==,type:str]
    version: 3.13.0
