apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-base-config
data:
    mosquitto.conf: ENC[AES256_GCM,data:RhpKY+ETwbgEKqdC5AW5VnCEzZFrTvU7ATQjz3+Aa8k9bPFmSsKvPoSEgGM3W4VS62KHKUOQkxw70j0eL6lU4bduvBFIQYgthNmnhRkeOX+YMl2ANgioUPWurdPsh2R5+X69rnLvsmTPBBJxNyWu/een4uSRIgKAtd8tEbO9T2+EZG/fYGWFOm8=,iv:MbE7Gsm4r1Cqtkxi6JfxF01ztTjv3Aw5vnzs7vhbDAw=,tag:fY/s7H6+z+7KL0QZxSUiOA==,type:str]
    password_file: ENC[AES256_GCM,data:G0KjoTo1aHh+yYiHMBH5aUxzQWlhaqPHCU6CGanmdj8olTJ7qQQiPP+LrqPuNf+5bYb/M8xwU9Gv/nBc9eTjdUqfsU883bJOU41vAHpgzOKUO55pdgShVSj8GBYkaFOBj67mtsCujZrxq/uIcBAUZQ0zEfot1UolDl0O0pFYFLFQfgo/4KRLH9uv1mOzsFKodPEktWRQgRSj0cXIjbhdt/UHxlrMbUq+XPb+8CywvulcW3RWA4IxGe+E8cZIwr8ETlsVrZmU3lh1OZ5yoC9cknU6ydcLzPBEr6BKoZZcwZbfWnn9TEXOD/t1zRitDdcnP9N7DUlWRYUdvCUGFaA=,iv:c7ViXyaez/up7t6Oc6eSJX7+3gGznE9UAAFa8QeC2mM=,tag:Np+RtJJ2rQmFsa7pC1NwrQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBienRtWDVBWFVTVm4zSUZX
            L2gxc0ZZeEZ5MDNidndZak52dUNlVnk5M0ZVCmFuRkR2SFBrUlczKzFkWitFRyt3
            ajZHb0lyWlpBQktNdmhwMlJjQkFQQ3MKLS0tIHUvSzdMRHllZnNLWHU3Y2VGSmVB
            OHlRNkhZZEhybWNyNWZ3eWN6amhBN28KIcWscQL09GNRDFKK5aF6fKHk/dXJBFFv
            yzS2hVM9ycuuAzX7GjY97o976GQnb/IoulF+j6J2S0bbGo+SaGM3/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:45:39Z"
    mac: ENC[AES256_GCM,data:h0fK9rw+b4KZC5HEEeZThYyPvNtL+7xDrLfYeTw0Vb06ym2RCJiRSVPoQ1WP4h+JInUANDWySNleYbtgswr7ilUR9dRGx7IYPjJ33KQvtJZoP4GVVbsz2rHev9J2w5zlM1nKIMmXlYtiLkNk8x0lBd6M6J1IRaSxrCPeq9tyCGI=,iv:WKLxqVKyqbeDCsQ5IfqtsfzWyC22gl+7v8/SOXHIss8=,tag:F+aVjvha88aYK28J9Qj8LA==,type:str]
    version: 3.13.3
