apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-base-config
data:
    mosquitto.conf: ENC[AES256_GCM,data:RhpKY+ETwbgEKqdC5AW5VnCEzZFrTvU7ATQjz3+Aa8k9bPFmSsKvPoSEgGM3W4VS62KHKUOQkxw70j0eL6lU4bduvBFIQYgthNmnhRkeOX+YMl2ANgioUPWurdPsh2R5+X69rnLvsmTPBBJxNyWu/een4uSRIgKAtd8tEbO9T2+EZG/fYGWFOm8=,iv:MbE7Gsm4r1Cqtkxi6JfxF01ztTjv3Aw5vnzs7vhbDAw=,tag:fY/s7H6+z+7KL0QZxSUiOA==,type:str]
    password_file: ENC[AES256_GCM,data:HIbFGw/tmNws0X7dWi5jshH7yBdlXHqvlwXpJA3jiWo4lcRA2zwogd3kTezdNK+2c5394FVo75TXQ3sSi0tQrLNmKnWPZXkm+Gb8NoItec7Xk9zS0KshCSR6ipYNb2IBZBRu06fIkC0lpXbzq8y02aCgfZh9zzOlT/rxwE7H1T4Tz3NNvMnKWErGoeHXn9uKaLyfwpxf96aogyjHWiStEtWur6ZeGvNSXBTGmB5qHgxnQkRvH8GybeYiWAG/1GRu6+WNDU7xUoIpqt9p6u2MaK/uQz5GX71p88q/Dg1JS/MDXHqrJsBJmI9Ulr7yVv5l6qVIY29/6lY8knWrk2gg7S7ljVezUjfbAGbwRLeAOGpIMAf1+MrinFcuNXKwL3aDLCDXbuxRrpKK8H5Xyk4mZdqz1qNBhsJz9yAIIMwFrYlo9ixzKcmmUQ==,iv:IwrVoaNBAiQB0YQZuLdByrhb96bokAJ/tB1wWjN1sQI=,tag:q7EHS9+5sNRKSaqcBwBttg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBienRtWDVBWFVTVm4zSUZX
            L2gxc0ZZeEZ5MDNidndZak52dUNlVnk5M0ZVCmFuRkR2SFBrUlczKzFkWitFRyt3
            ajZHb0lyWlpBQktNdmhwMlJjQkFQQ3MKLS0tIHUvSzdMRHllZnNLWHU3Y2VGSmVB
            OHlRNkhZZEhybWNyNWZ3eWN6amhBN28KIcWscQL09GNRDFKK5aF6fKHk/dXJBFFv
            yzS2hVM9ycuuAzX7GjY97o976GQnb/IoulF+j6J2S0bbGo+SaGM3/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T02:05:08Z"
    mac: ENC[AES256_GCM,data:OhkpNSePNGAsa8KmhkkDsmzQT2Z9Wq+MIyLeSjTnxT17TIjyRqOQpVRgEAZtCnn6pme1gTmT3IOpOi/nF5Q2EmIpsKnxaJiiYWX3v+tSVYIY2hBuwyIShBGc81G9+x5YaWlH5kBXvz8PmKyv0j53rzKHUDvqWM0cuRi5p/Dm9PQ=,iv:PEO4oQb9kLcajMkg7Sjm8Mm5rrBYZqCK8VkBdKAPy+o=,tag:IPICOoMGF1FFAhZJngCcGw==,type:str]
    version: 3.13.3
