apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

commonLabels:
  app: open-webui
  app.kubernetes.io/name: open-webui
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: dev-team

resources:
  - deploy.yaml
  - ingress.yaml
  - service.yaml
