apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai

commonLabels:
  app: openwebui
  app.kubernetes.io/name: openwebui
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: dev-team

resources:
  - ./deploy.yaml
  - ./ingress.yaml
  - ./service.yaml
