- op: add
  path: /spec/template/spec/volumes
  value:
    - name: homebox-volume
      persistentVolumeClaim:
        claimName: homebox-pvc
- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value:
    - mountPath: /data
      name: homebox-volume
