apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homebox

resources:
  - ../webapp/base
  - namespace.yaml
  - secret.yaml

namePrefix: homebox-

labels:
  - includeSelectors: true
    pairs:
      app: homebox
      app.kubernetes.io/name: homebox

components:
  - ../webapp/components/httproute
  - ../webapp/components/pvc

images:
  - name: my-app
    newName: ghcr.io/sysadminsmedia/homebox
    newTag: 0.26.2

patches:
  - target:
      kind: Deployment
      name: deploy
    path: patches/deploy-container-port.yaml
  - target:
      kind: Deployment
      name: deploy
    path: patches/deploy-add-env.yaml
  - target:
      kind: Deployment
      name: deploy
    path: patches/deploy-update-resources.yaml
  - target:
      kind: Service
      name: svc
    path: patches/svc-target-port.yaml
  - target:
      kind: HTTPRoute
      name: route
    path: patches/httproute-add-homepage-annotations.yaml
