apiVersion: v1
kind: Secret
metadata:
    name: auth
type: Opaque
stringData:
    apiKeyPepper: ENC[AES256_GCM,data:Fbk1+ZyUBZZwG6DQr1GbC6GQPcW3qznjxmq71TqDRWWEYMQ18hLEgO/Xnh22Lb9xlvwfTYrqmX1gdj56MvZvjA==,iv:Pg9DxoCMXoRdqNFCgh9yd4ZgGOw4j4Lo3fPOZRrYNa4=,tag:Mo/AhEbMOMOXjxWRWpeHtQ==,type:str]
    #ENC[AES256_GCM,data:gJUWJ3Xc3iRjvHky1dG51mQm6cuVB9lMapc3GZNDaFuEO0bMDsZx3UHtRf3UQsgYOTl816KAZK1BavoeizlHNv89+vhW,iv:PZIuTx6qip/Jr8FwtlUPVAKG9NcY3lWQlkVJGlK+SNA=,tag:TtAMRY/roQtC1h5ekVCaZA==,type:comment]
    #ENC[AES256_GCM,data:V/yMyDg1XvOW7Sw1OaFf5Kj9XALQzO3BJGu2zA1EI/XiqwKRXOh6eoW/F3cwwrWamQ55e3LUmw6yUo7hMMU=,iv:w2lqwE0v7XU1q4O/7C5/J7mawBlgtndSmS+o3iVWtRM=,tag:Eu1zsgH+aJ3FFuGowzJkjg==,type:comment]
    #ENC[AES256_GCM,data:zlc+tX4++XaPLdbAyTUjzrOD3z+Qs0ronrUSiiJ4oPX+XV3Q4HgY5HtDUr7PgdV8BbfgXJ0GcYyTcu/slf/E/xhFr6M=,iv:v8vi0uQWTjfZsw/JYG728hb3M8P24q5X2izDiEHBKLE=,tag:Rj4TP+JaRIQCT9+Fw4K+KQ==,type:comment]
    #ENC[AES256_GCM,data:jV6U6TmyCfczYF4eHT5jaJhDkOiB0095CYovkhCrGRyhzJ6C8kBUbz3JQQ==,iv:vh8nzolHmJkklcRv5yg16g9Nq4BksJvapugoTfMxn98=,tag:RrxPSwpeOtMP8ZGmer+jUQ==,type:comment]
    #ENC[AES256_GCM,data:aLaiqRH8l5j8f5ZM5Yu53yAvfxr9s2COzmB6foBt1V58NSMFc0jh3yxw/IbKc+Y/mJeaU/xyZ0A17h31zVEsGNmW2vE=,iv:6LYfPf4NA1Fm59QsrPKfF15/U+eidPA7Uyp+nGUbL2w=,tag:0ssCw1ol5l8R/Nz/pgTC3A==,type:comment]
    #ENC[AES256_GCM,data:3MliKmYO2Lp6XjawGZES+3+NTfDN8Z/3m4wHri6+hSbMURS0oeiAER+DCgH0nGJ3EWO2pLO6Dl7QkojMrkZDor7MYWWZ8A==,iv:nGDSqEohIz55FDej5me92fveAODP79Hv6BQc8aV7Bcs=,tag:zi2IzNKltlrZDOVgSXNVzA==,type:comment]
    #ENC[AES256_GCM,data:iw+MKIdcoorVa4yrbYnetRyudGreKawnvCef1J5qAuCw2Zefmwfz4sBFaPg/xCwTnKDXz9O/WmRM1qz1fX6szlFV5bE=,iv:q6lYa0m8R99YP19k0DgLu48NgrthuE4YZsAKIrYFY6w=,tag:YdF2K5JTzVQ4IOKJcz0uzw==,type:comment]
    #ENC[AES256_GCM,data:+/48SWqdSRqy2SUv/pV5lJi8PBN9gkEsGIrNhrl/qY/eSKZyRWfOCwGMiLRPOGhVyAk8Z3vjG2Kf,iv:4lS/KYJNq1/o9oRVttYc7QDMo6WsUKPZ8MGy5FajzMY=,tag:HtRS8pb+8HSdWwqPoW3JSQ==,type:comment]
    homeboxApiKey: ENC[AES256_GCM,data:IihJKo18o2nfXRWw6O2FYb02i5zZCmEKjRH8wqjqnFa1,iv:G5G8WQkuCXTBOh2HvDE+Hn4x/wiHEndOXjQ+t+tLpX4=,tag:bwp3EyLMOcBSMLVvrbOwug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMFU4UUdUdFU5VWRPV0ps
            Unk4cnh0L2IzdXplUmlHdGQ4WElYSzRXQWxnCnc4dUVneG96WnZ2VVN6bFZTeWh3
            V0ozYUdWa2ttMU9tUXMwVTBEZVFCOHcKLS0tIFQrclRMMlhWS1BDR3hwYzVpZEVl
            UjZIYXVMTDU5QUxTeGxYdjVYNG9sMDgKs7JJZ36Zbd0CXwMX+qPCTom5uwLWuq6b
            bn4Ze25HcPeigYffF89BHXajrK6cSb5JSKFW6oXym3vj/72mt5NQ3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T02:59:14Z"
    mac: ENC[AES256_GCM,data:NApS7NXKWHekI4QdHzqzW/moClA84U+wlB9O9QPIJRw5ruSgYkmrzq9I8pe3TcKiY8H3++SFGy9jgPFEzYFKDpwTovg+pptugNZ+4KtUpriSNecdhWhEGwkkHGzXDCPCw+uOk6avSlRocq9fD1XO3Cc1arHUJ6JjmS/Fqa/tzTM=,iv:TWNxkCEFILygm/3CmGp7PcKjOEKf8Sy0vnQ9mXeN8oo=,tag:KyLqLT6NG+U7wFopcSVGYA==,type:str]
    version: 3.13.3
