apiVersion: v1
kind: Secret
metadata:
    name: auth
type: Opaque
stringData:
    apiKeyPepper: ENC[AES256_GCM,data:xJqVe0xTaI1NOs4jprtZifWSXaB8BKXmMODFgRqDoiYmuQVc8xpb6PsQUA2ezeQZv7HoZsy1bs/+7MCWBnrW7A==,iv:PKf6zPPCM86qp3shIY35qlyV1RwMRdypvLiUxL7VUZY=,tag:lLctqiHnthbyFezaN6aWhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS2RXQlRoWXVaajB4WjFi
            U28xbzl5OXhxWlhNYVRrVWpKRkRSSENoUXpRCkwzN0dOM1lsNG14K0lHQ0s0ZFRE
            RStocmczaXI3akp4WnlHN2VvYmhXZ2sKLS0tIDFZWExEOFZQQjZFdDBVYlIwc25F
            Q1pTN3kwZ0pXUWRVNkFRSzgrd3k0bmsKtq7eA7O1fl6Naw3lih4vJRRYrArNDZko
            8wuFP4ms7q3fttZb5qrZ7d/uM8WU+CMwuTHr9zA4jFvfCNutM1tDBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T04:21:40Z"
    mac: ENC[AES256_GCM,data:ey5dsiq/ZagoRd36wpwcDPpXcZfL34PwKpNIFEeH2Lpn/Zfi1gNt4r98xZtvHGHE6iu1MbEWe+ma+PXzY3585VZrx7PScPxMDsb3THIkrh3XRB+rr05ZKnRV/MGeu8WgnpzKoZ9Y6m5hBjEfxpVZNo13E31wVon+cbphlC5eftE=,iv:06+06PsM/1y/x9kqhMMGhIVRm7VzuW6VKjYfIqwSxZk=,tag:BSSD8NDiBYgRFySG/4N58w==,type:str]
    version: 3.13.0
