apiVersion: v1
kind: ConfigMap
metadata:
    name: zigbee2mqtt-helm-chart-values
    namespace: home-assistant
data:
    values.yaml: ENC[AES256_GCM,data:dFTwv/mOZ3sTkuDdg7a/7Y+65F/P2PPQqp8EOe9zpf3lh4Him35kA0g/Ga+tIW2V7hBRnB0DJ62ccYkcmDUSPp8sqCyg2GKbkw4tLHUvzqL/7TmHjbDdOOFvfdEuDJw9vlkleeRSv0h5FXRzsaLMfv8JepBTqe3YfBcfTdhSmi2ez/qjDr4zCFf6ulPQjVIJkoG2RLE0aiYKqCCJ+bxXeRYg0hcx/tBo55STzsfBa99RlABAkoV1MT54/WXQ6W171GDjSTqZvqROA58ZQLrVkSzH2xGHzxcnBVxtaenSWpdGqdj19o4mO0FsYjR5/b9qyTpX2ma5yyFZOGs65zmvnRbe48cr/MboWmLDfL4Eb3NkdPCIoMmVGT0JBV7sm/sLdDSmiOR0VuLNpVAwtd5AQ/RoMctn0Wyk0kfgPqYwHjsVQytk3ycJGYTv12RFdZXoZ7qzMhSfRMVdAavPJu54bL0LE+XH70yomaNE/AckJumQcrfokEGC9g8z+h7SL/1AGUj+v6cHgOsq5NxuPGISUkk+1PPzHHmVD0PXs9+VYH8bm3cGVl/LMpWJj0LHAL4LL9wFfU6t/TgvA2VrQibc52/CYwkKMcuWMVbRAapjJ5+PDCRVy3FBRyb2uBL17nEukSAKa+Tbb6uBxSSJPjH8PQvONccAhqJooFoj7lUBptRr1h4ITdgHWt/nFQPTtgAoevBaowaPKIrwlx7j7HOoIgG2BfrDKKDcemUl8D2obKlMZnRGqHUqPEZQVTOvccbdI0YmxuKUgpAsO/bJRbeAYPJRNxsv4stIdZa8ZOgRm8xWN7K74P/GYCcBBjtcGuJBfe9owYiNKx2oK4xw1eN4TU3086q133N0Va1AgJ1T2ONE9gibifIkFswbO08cSwtvHWYIWwdX/St+CTwmbxTQqMa24fy+6goZhmr1m3X/IRmOXBuvspTrs9cJy2azuUSoW+Afh1q90jO4KQckgTZDyvEHHtMRaSJ6yz6qm+DxsmrxQco5VLLKOMjwvkkvG1X7knOcLp8ZBXLj+kkJMfHHb8vE7q/PqURzNq/FuMb6JL5tRKIul7x+TWXF3ODMZxh3Snm3Y4vbYdCDysSNdvPSgrURFJ7k17a0hyyiHGkIzX4Q07UzKhRdiuFmTyKkZhWUQ8btx/rZLS1m77DYCL6HQqBvLsjyab5PhaPmDK7KpuaGyn/hcxgjrghj12FClvDbMP0vB740S3INuRVda5bCqABbQAppszzLKXTe7HxM/Jl2z+SRTsXkNBjLfyCLTSQRDmj4kaWYEW+PrYz0IFqRXpAWG3P+dK3bEYtA9rz9odZgXYaknSD/4hYqCvUABoPJDzs5XY+koBR4RtrpebbMzVtoAk8tCJnt4NF44d0Z292CUJjIrr6rOOlYDsqX5wjd571eha8rVXThkvWuhLKnYqZ0Lez13MGv900NhUPhl62GXNvyq+m208bQCu5APRr208bMaSgsFb090QfbydSzoAPmPnpe8XcGnPxGXVwvNVJxOwTqWZ5Sxw==,iv:/g6/jxgO+aM1i4L4zfjUZnR2Z6JWj4WbFLTVqH56flI=,tag:gz275XIITdC+itGc1q1fJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMGYxa0RESG80bFd3Nmor
            WEhvbjhVQ25rZXFHV1JXT1M4NEZyTk1ITmpZClZ0dTA0WURJZi90SWlZRThML3p6
            eW85bHNZR3piY2V4Vkk0THU0S3EyZFUKLS0tIGlicDR0bzY0RVViZVlnNnd0RVRZ
            dUx3SXhpYUxOSEZ4TWVFSlV2YXpYQ1UK02Al1Yqhv8VzHeToFgN6hE7EG9gRL/M8
            uRnT5lFVVuMF/qP4fSLIhkZsW4SiMVaJ6h+7SuUfATydRrk4FeeJkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T04:57:19Z"
    mac: ENC[AES256_GCM,data:hegT6w4Q4eb52j1ghEw7+t15acg8SgyGZxihYrqOwol43jyX7nuBRMtDc4fE/lWHugd46wT/thHbmder98X21kJ9y6Oh86KfhT0l6diPEjUJK+kwSU/fVvVrLTKmpbDV0gXyCT0oJGZhsHkc7Nj5IkCqQxZXgKrkcZevdIXaBPA=,iv:LwOESWulmVCfSe3T3Dw2yia8FBh/Khhr89G+YQutwPE=,tag:RNBzJbYcLAZQ/cH59xkTLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
