apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: godseye
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 30s
  timeout: 15m
  prune: true
  wait: true
  dependsOn:
    - name: cluster-settings
    - name: cert-manager-issuers
    - name: cilium
    - name: gateway
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/godseye
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      appName: godseye
      subdomain: godseye
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
