# Common configuration for all Orion nodes (both controlplane and worker)
# Install disk and image are set by hardware-specific patches (config/patches/hardware/).

cluster:
  clusterName: orion

  controlPlane:
    endpoint: https://10.50.0.10:6443

  apiServer:
    certSANs:
      - 10.50.0.10
      - orion-api.norseamerican.com

  network:
    dnsDomain: cluster.local
    podSubnets:
      - 10.241.0.0/16
    serviceSubnets:
      - 10.141.0.0/16

machine:
  kubelet:
    nodeIP:
      validSubnets:
        - 10.50.0.0/24

  network:
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    extraHostEntries:
      - ip: 10.50.0.10
        aliases:
          - orion-api.norseamerican.com
          - api.orion.norseamerican.com
      - ip: 10.50.0.11
        aliases:
          - orion-cp-01.norseamerican.com
      - ip: 10.50.0.12
        aliases:
          - orion-cp-02.norseamerican.com
      - ip: 10.50.0.13
        aliases:
          - orion-cp-03.norseamerican.com
