apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - httproute.yaml

patches:
  - target:
      kind: Namespace
    patch: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: irrelevant
        labels:
          gateway.networking.k8s.io/access: "true"

configurations:
  - nameReference.yaml
