apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:GCtAOKiVHw/lcBDhaxFU5Ba6FINAGhKn4aOs7uoQo/xe40S2GMY8FATa2wIn1i5afPzVL7s=,iv:ZfVYRfJFd/3y1kqpoFynbZb1si7cpOtBZHgKF1M/sAM=,tag:gbJe3SdLBRjA4m9KWs6aeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSkhKT3NCRm5UNTE0dzEy
            S0E5SVBpQU9xSzlsd29jRXlGNnJJNzQzU0JvCnlZMkdvVzg2d3RSdC9keG43Tkgr
            RDdYQUFsd0Z4ekZ0eWw3N2xlLzVZeDQKLS0tIEdGMTNLdHltcTVOMlllTU80WHJ2
            ZkdGbFFSQnF2RERnZm1QdWhrRnkvU2sKFaO1Kc7fe/yPg3AfD8TTuGKFVK2jj3Je
            hAZEsqh1BwWMLKobEO840YDwAuMlWKoLEGhU9b7Is1NkMoiERBEmaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T19:40:15Z"
    mac: ENC[AES256_GCM,data:AVFaYBeIP41Idt3pjVg0ADGvUuKfDCThNcgzmaQaSlmcp8A5F3981he/dVC9VsfXFmBNBeGnj4fBkgfErTxTt3mucWS5UwPT9igBPzgiaT50CpoYIcKnetOddFPMCI2mUQx6yEfzSHvxHYT/avuTzlD5am00bLXgATz8uiGrK+0=,iv:SQmFbmKiDQHvztytYScrqnwicRzOTnkiSp2d4zVjqqg=,tag:bMK11jiCqhpaJQJEh7ubpw==,type:str]
    version: 3.13.0
