apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:5KG17Dsqa4UMggyi3+m4f2BeH+IPbA==,iv:QWie/T97X4VuHYodaxV6LyNbycZcv7oayFVMQ1YAmFU=,tag:CLTO2VA894o5tzhVoHokWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSkhKT3NCRm5UNTE0dzEy
            S0E5SVBpQU9xSzlsd29jRXlGNnJJNzQzU0JvCnlZMkdvVzg2d3RSdC9keG43Tkgr
            RDdYQUFsd0Z4ekZ0eWw3N2xlLzVZeDQKLS0tIEdGMTNLdHltcTVOMlllTU80WHJ2
            ZkdGbFFSQnF2RERnZm1QdWhrRnkvU2sKFaO1Kc7fe/yPg3AfD8TTuGKFVK2jj3Je
            hAZEsqh1BwWMLKobEO840YDwAuMlWKoLEGhU9b7Is1NkMoiERBEmaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-31T00:01:05Z"
    mac: ENC[AES256_GCM,data:Yewh6owCY2o5MOtIWAs3ewQr1RkGau25XV5fRFHdhcv7wp4zaDbjbknz56hM0sxwByu9LExhmm7WjY86dXkPqvtBLw/nnIJHJLZM6fmRjQGc7bAGf77nmVRvrqkhvjo2aFJeAHlGFAcblIppdD176ytuxrrYdYpDWhoAFY0jD90=,iv:gHNk+YCimS2esLJC/FtZAb7g+8o74DNUo2raVfmc6sU=,tag:65/NQTWhfspNNF72abp+9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
