apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - secret.sops.yaml

namespace: hermes-nas-ops

labels:
  - includeSelectors: true
    pairs:
      app: hermes-nas-ops
      app.kubernetes.io/name: hermes-agent

patches:
  - target:
      kind: Deployment
      name: deploy
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: hermes-nas-ops-secrets
