apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: hermes
stringData:
    API_SERVER_ENABLED: ENC[AES256_GCM,data:GpCpvg==,iv:8rW8UXU4LXSIcS11mD1nE2Ua7+k6o/RdbKl4HJCyNHA=,tag:B7pEpnFLQ7MEqqn+7zGDCg==,type:str]
    API_SERVER_HOST: ENC[AES256_GCM,data:8zGhUvey/A==,iv:Rau24qKlx1SnfgW9RTUE+7h7j0U5e0TqAb6loHWgdV4=,tag:WYSi1iEUy87rc3r2nqZZLQ==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:CBkUzUAWpmG7RCVYKaoqXtzQ3RoNu/6RjayzhYjcMtSr7qT25Iu0+0mPEMStsOgcXHz6O+7eRqhobOjqrnllsA==,iv:sq+vdcQ3m80eythNyQcVBlfgJhM/spegVeQS35DqrG0=,tag:t2Zve/N3dYtalRTqQNEiZQ==,type:str]
    TRUENAS_READ_API_KEY: ENC[AES256_GCM,data:fbAvt7bUZSs327bSrUj4OgDGSU5oicOdRH6Lj3Ent1UGBiwOZvV7L4c=,iv:MyFj3j6eiNATlA0/fNV7/CKSDK+Jf+UjcQ4p1QzW9jE=,tag:guwWkN75mahQg+6Kk0V2Qg==,type:str]
    TRUENAS_WRITE_API_KEY: ENC[AES256_GCM,data:ikM9RBVH9L9Unlcan2dLgF0EtVy+IsWVVk0XeWxxzsiR00uJrNAexewLBQ==,iv:kg3GdCZwhxJHNhdriWCZvdQUpFyMCaS+yBta2wQmy3Y=,tag:i/hqIv4Vs14EExsKxGKwlg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS08zSjJKd05Pd3NvOS9p
            TWZWcUE0Q3prTDVXL2N4OHBqM203d2JCb1ZJCnJMR3d1dlVaSGhBakRRRDdnZ0ZZ
            cDcyN056ZzJRaXlyRkgzNDNUdVpJdXcKLS0tIC9ha3NVOVBWOTRqZTBzbDdHaExl
            M05saVFSSmdQS0kyMC9HK3dOQzFRZG8K9w2zZc9ykBgCbYkgaJXJHf1cIiQ1UvLK
            S7Om9+72YG3Yq1HqJJ+57XXs2yXOJXTh98R3G2qhizkBa70xs/kuPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T17:32:22Z"
    mac: ENC[AES256_GCM,data:tExjhHYyRo0drVAWMGcU1umEUg3D9GSHxalklKBplcL+8BPZGIKXkm9v6f1zPlWLnZqyxQ0AWa3Vhi/co3iOlYM3OnDJhjGYy3mlFiAnhRYkr7Ra/Rdw25zuwvaWDDpU9hYPFbKuJkhdd0fSwWWUpVJKxhj3WYeKKLZabhw0OOU=,iv:P7ev2pPpTDelKj/ud0IZGpLtYNpwUczuq4YvxCQYnik=,tag:ByfJUSMpabhbDycBnUDFvA==,type:str]
    version: 3.13.0
