apiVersion: v1
kind: Secret
metadata:
    name: hermes-nas-ops-secrets
    namespace: hermes-nas-ops
stringData:
    API_SERVER_ENABLED: ENC[AES256_GCM,data:yU5E8Q==,iv:borXkOQwftIk7CKDNZLXRBU47h1ljZm+2+G1YSKJj9Y=,tag:PrBnrcoKVVRpPEHmLpZpng==,type:str]
    API_SERVER_HOST: ENC[AES256_GCM,data:aDuYeNYdJg==,iv:50aGflF70c8UV2NZWs10ZZDSfbV0Ajpfk0+E+DFsqoU=,tag:eSTJcV403B9tHD61znoYpw==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:JXms403+tokwGuXO3n3gTkIijKh9eO60g3Bk637RZFTalTtE8CU2MEX5/ZwXi7RtrovDnx8U6jAjO5Fu/sRWMw==,iv:XiQ0IH7F/+rlufmQS47INJJBIeVFOYJCDY7vDLTK2kM=,tag:upEhJhqDWFcpHodV3W4W1A==,type:str]
    TRUENAS_READ_API_KEY: ENC[AES256_GCM,data:915jBWWSomjroZs1f1vdY3zUbp8Ufct1csyHmdEwvzPEXP3Yx/n6Hk0=,iv:HorazqHaVG6133j/63gqKo81UaOOemcDDIwFISsWqXQ=,tag:PJn5VBMjvCCW0oq0ApDVhg==,type:str]
    TRUENAS_WRITE_API_KEY: ENC[AES256_GCM,data:RpC1aKxgA2Mv7sPGIRSZppDjT0cgw/Me+Gk65ys/W+J5iNKbieMyvuGLSQ==,iv:78xpR08BjRgqSuFZU3prVE85c2l2KMSmipDW4Ht9DCM=,tag:iODjXymfd33rpdYaWCzJOA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVUFoTVpuK25UKzk0UURR
            eDRBYzQzMW1Gd1RobmpwZVlqZVdWRGUwVUhzCmtSM0Nhem41dHdlTG1qa1l4SDhP
            aERxN2FqblBmRE95d3p2cCsyWk13alkKLS0tIEZtRmdHZmhsMm16dmNjNnhyOXhU
            R2MxK2ZDT1JJN085TjJUeFcweHlJcG8KxZO3eVWxGFMcVqb0z1cq7hpK1QDd3dZM
            slfUQ2WA5QWH+VjMzZ5+k3xzf5kt5MlAeFMvhuZWU5GHMawJLJyy3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T17:20:20Z"
    mac: ENC[AES256_GCM,data:F6j30Vow0GAMg84/PHYXSZuWT9shKedHDNV0fOz147qdAytl8N5Bmcub2BL+z+X8K/3ftLinVsz4OxTCiSoiYFeYRNFKQDiJIcSTC2TgFH7jP3mhGZ3aEtQYcSswHs99JD1z6tSpQPS4bjle89iWqaRT1YoBJ5YHHT5SkZ+yOcQ=,iv:D8gF9+0J73qVcn8FIrrnkNzX8WUFfjmRZ3KAM2FxL/I=,tag:v1IwIIGbRKVliWPsqYRbBg==,type:str]
    version: 3.13.0
