apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vllm

resources:
  - namespace.yaml
  - pvc-main.yaml
  - pvc-aux.yaml
  - deployment-main.yaml
  - deployment-aux.yaml
  - service-main.yaml
  - service-aux.yaml
  - httproute-main.yaml
  - httproute-aux.yaml
