apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${subdomain}.${domain}
      secretName: ${subdomain}-${domain}-tls
  rules:
    - host: ${subdomain}.${domain}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: svc
                port:
                  name: http
