apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - DOMAIN
      secretName: DOMAIN
  rules:
    - host: DOMAIN
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: svc
                port:
                  name: http
