apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ingress.yaml

configurations:
  - nameReference.yaml

replacements:
  - source:
      kind: Service
      name: svc
      fieldPath: name
    targets:
    - select:
        kind: Ingress
        name: ingress
      fieldPaths:
        - spec.rules.[host=DOMAIN].host