apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ingress.yaml

configurations:
  - nameReference.yaml

vars:
  - name: SUBDOMAIN_PLACEHOLDER
    objref:
      kind: Service
      name: svc
      apiVersion: v1
    fieldRef:
      fieldpath: metadata.labels.app