apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole
    namespace: external-dns
stringData:
    password: ENC[AES256_GCM,data:v/0iTOpZ6LUaVIU=,iv:qzcxqNJlpcxY2/ar6MlWS++mSUj4AmnwLO9M/8KGj+M=,tag:BJa0COkQm6tBOoIMQ5gS3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dURBb0VldVRoYXdzaWp0
            dzJkS1VhdXZnS1ZFRjhFQ28vT2tVbG5pSlFvCmZhU3pJUlp2cUdQbTVDandqRks0
            SUV5Z0dtK3cxeDFMWXI5VDRRM0tkRVkKLS0tIGszd2NZM2hjK2ZFMzlHYzU5Zzl1
            OHZoVEpyVXViUTBBMlA4R05rbE1QcTAK1C6a+XAzB5LmYliWtnTBJvkbPu4K1xsi
            7aRZTeUI9vxx4kDcCQPDVhuLDGX0t4Ca/YUAIb+MXWGM28Tr4JTzEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T05:28:28Z"
    mac: ENC[AES256_GCM,data:MY70g+aML3mPh3/FCVLa3v+emmSKzymY7V8m6ZWHv05qUlACcgkJDyRx1L/L73W5fc/O5S5/x9aMk8s57bEZ8L2RMb/RyWPt4iwF3Bg3pTwZMakZf6zExjbHH9jffUDQDK4EplgRX9wgqXF5UDWYkJc2nrQdce/JIsVWtUIdx68=,iv:hxHUJdhxlRYl5UbwnRpqC4tGsnFlH1wR98tFHEmKvE0=,tag:TSGBfrlCsxLK+8d1k3LR9A==,type:str]
    version: 3.13.0
