apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole
    namespace: external-dns
stringData:
    password: ENC[AES256_GCM,data:Hib0pbO05AQ=,iv:s+72ac3CBmk7//TX5thJxSbTcbv6m+mPnt94efrKpBE=,tag:lL7PaG6bsQp0SExGJfUKMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dURBb0VldVRoYXdzaWp0
            dzJkS1VhdXZnS1ZFRjhFQ28vT2tVbG5pSlFvCmZhU3pJUlp2cUdQbTVDandqRks0
            SUV5Z0dtK3cxeDFMWXI5VDRRM0tkRVkKLS0tIGszd2NZM2hjK2ZFMzlHYzU5Zzl1
            OHZoVEpyVXViUTBBMlA4R05rbE1QcTAK1C6a+XAzB5LmYliWtnTBJvkbPu4K1xsi
            7aRZTeUI9vxx4kDcCQPDVhuLDGX0t4Ca/YUAIb+MXWGM28Tr4JTzEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T05:30:43Z"
    mac: ENC[AES256_GCM,data:6xVMsSJdi7k9BP351d3whoi1CHRavB74s1AO9GUwqxn55mwGWavv9yGdAfixxV8x++l2RtMax73EbE0dkqmG3PXmwyGeO0UvqwQYlIZX64HM3dH0H4oxFPsAlQxo5IlStqVcuTcbsGqNjkSrfrenJ67NqI6MxB0FHjA9dbLgbtc=,iv:zxL/970veaU8l0e8gOSuO4nNXKjH48R8mOj52N5+Lg8=,tag:7Y+CLj/MPGoloHRD68PVBA==,type:str]
    version: 3.13.0
