apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  domain: norseamerican.com
  externalIp: 192.168.2.240
  metallbAddressPool: 192.168.2.240-192.168.2.249
  democraticCsiHost: 192.168.2.58
