apiVersion: v1
kind: ConfigMap
metadata:
    name: zfs-nfs-helm-chart-values
    namespace: democratic-csi
data:
    values.yaml: ENC[AES256_GCM,data:htYAwgmLYeyXlYHbCAvNexBPPuKXFIM2t3JSpQBaK4fJBSJn+y6XYd4qwsbgRhorG4I67Y2a29h0qBUqtGZrJ+XPIIQJMmgwsuEfWncXHbVtLAP2+ObGg54jcq9mf8m33JDTwGdr6gbjXrpDNL/Nnm8b08hLKl+4y1YgDwIkI+BwQDt/FLtpW/h1XQhuePI0VVQGhOTKdZsqo588wuaqJ3WLuFczVhLwxKpvKqRqXc0kJAUh8Ehr7j1nYX3MSi2pK7ZAZyiBT34WWanZwyfXZ3jjKSmHyQoTHOVrdEGo7zUyBys0qQA6DQUm5jLYvG+j/DCiKCopOIAA/oEwt8oux/6qLko9b0bpq8kV5qevuJlvS6XXFEWePR8jeqErQSok0/TrQeCPSRRWq1NzKSCMb0aZFul0X2BaKGh4NkstzTNGIYvt+binmU26AybaPGWyVhByQpG8F2ssFyxBS7oIAuxA/I/0KTqeJpYEQcNVCsPvTFORbH5Hfj/aT8kQMb1OFeVD/koSC1BI5PQkccxLSLPovGCW6Ib8hsjCWz6G1ZXB+xPs4qDMFkatOCz9LdK5Z9un1Z3zlSTPTnsHDzz5HcfVnROPVnb8xfHJS0RZA0yBvgk9wRegy8WU1J1xJghxMTngRWvJijb7jdUrjF1EPOFdfwb06gtGhln+xUxWykahvDgisCLiX7AW7sI07wfTcmKY4PjP3nEnUiAAPqbFkMdqGNKRkm9u0JmxntxvlYxrc3gWHpq/lLJ9kuY6mMkJuQvlE2PoFTdptPlMXK9uzIrL+iqG8ZeFqItbo3XSDVvpM6ecrvEaEaz6LxtEN354c2HjfvS+smz/82+duw0ha+ws44Jn0ztEQZi+CIPVgMLqaqE05uy2nY7Gx0jFUeMmK7v7FiQwzy6R/I7FfMfhmSXeCYDBIcaC5A69MjVdsIN0dH5r6S0FCKSVhQdqmI63urlFGgspMKQmzkfT7UbzVFBOabLGb2ZJT/ZYTp7phU+bdH1yaEZCYU2JywhZaPv0aQPb8qu3JBCtJGBkk/Eshr7/jVBE11FYfBENSgg0O/K02VG68dOATJ0lEyNE+nubalH5TnW10wsV1RmyX1cbiItoDm8wiQ5nZae4SuLA1c2Kdq2VeyjdzHwF0Kq+RQDMwfw7dAq3Hi88/RBNEb83R8n56p4nPcwyKPEFfx3UgeI6Ma5tEXkEukPHz7tof3Ni6McycYHzOFBA/ydHz8xlUFxdyCsU+hQpHX7nG2145f95BXJbfyfxru6OMoyztQF4b8JPUb+zD1lqxWBzelTxV3lEdXyzOtyZebW+s68wNxcM9XikW8oL47ZgB8jxMKt2fDCEiPA0ANuhr5injEZkXkXtnbxPoQ2Pf2Tx0TGpjvR052RRBbUDfX2Ous79rG+jstGMijGELJ+G1jXsbjgqB26JOoYJMKYHj9RAgDu7O/czn34UjaUZxf4bUIWGYCjMSi/d58+7awKY/SGH6e3Kmr1s8EHJW74fNnYryKVuglqCXq444u+Ac76d2e45ua+05fayMJAX+bQ83krUEp/4OowQrLtnWvK878vGP9+iQqnKVzKj5/qJF1OBxC54t/wyT/ddSSirUViUrFrk6hiYlPwk5zqlrVHNPokQjRcZcq8DEDHN3A3sD8dUcUG+YSv2CLiY5nSnnXp6fCVFK7Bhvo1sZg5YhfsZR+2zHszmbwls8w6Q6I5o6GlrQYRsX+ZX+eYEwpw6dKLZjgy/+oiEVhL6ob48ECHRKwQGCMyULFHsqGKo0OyrfdO6B/4z1b7RGfqXcv0UyFV5arlyj2QyVzt0h0Vx6dOa2/UDY12Fxm9WimFAbntIynCOYtsHrf0GKBiaCwW+yD6OePClzQ5LB7EVU/aDQ1qb8gvDd5NxZYg=,iv:MXoyUFFLJ3BWFjLnJJXyA0HXMAciEw4k1p/6m2Q/nUs=,tag:62I4HwZsj7a7qH4w0hEqqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUUR3NVRuQ2xMeGJvazRs
            OXBFMUFPQ09UQ3lZUUJUUGhBZ3lqN1ZjWWg0CklOMkQ0eWRGQmdDOW5zR2t5THFP
            aG15YldKejJYUVFiaGxxaWhtck9ocm8KLS0tIHdJeTEvU05zZlp3Q0YwdlE3N0hQ
            a20rM2NRYWNBVWNmYWZFOXFxUkNVQ1kKwJrgPOucT48RbE1crlmO8Hpe0lf8rm5F
            t33ZxT0O4lGMuyezlzqiH7wa7ZuE1SknrbSvJiadGFTtOb46thv/+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-15T21:33:48Z"
    mac: ENC[AES256_GCM,data:dBGU7Hu5M3rpYSRUmtzhKKImW1n5HT689IejbnjXBwwAvHdqLmNi/mMmywwQgYhtiEyrnTriOdj1ovTFdBnW4f1PY5k8dhuO37W1Eove/bSGB0BypqBNomy8XJWkX8Dm06TLmH0cKSl2bMa8jy0ZkCTp55is8NXSj9iat8cGFU8=,iv:9I3Sfh9YoEN/rYQ+91BsqtJqvgzFdG7+TrLh4htEO0U=,tag:1d7cfWiUCuQj4LDvy9qeyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
