apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
    name: linkerd-trust-anchor
    namespace: linkerd
stringData:
    tls.crt: ENC[AES256_GCM,data:4HYLyQAeMOokmHxxgmh5gSSTqNNQj0ld9jxfmrP0MBJaGMQ3sdvyEUY1esT8PP2A2gKC0NjmvBI0m0FjftNKdnSE7oKGVpM//aZXF6HVImjHCISJgX1Ui7CuDO5FA87sQmMNE1xX0JGAWQoWicBr/4L9fG/gbLgbvrhpxIiCwAkNvvgaSYzRZRd3dB1VntFt3WWaR8hXkKduAO+R1MNJMktGcWSfejDDA6om9TQb3Es6QF6Ut0PrJ26XactoYC7iESj5bqCnt7PsZaJCbxtmJySI/4Pz9UcUwaWAUK0YDaqeiZNgFREoMBOZFkASyouZQhPhFD8G0fbLfQ+Mlnwf9XkuvUZfJ4wX1oMtRlFAd9AWhcAzOiRCTM2/3AZ9WmgwI5ItY/dBNauRIcIT7/y6Zeo/uucoIVA1URZIsuALM3t60MqIbPs9QQnXZLkqK6KYxVBIIjUbxRsGP8oFS+pi0uFH9v0mTuk/fzhS8lhYVPs4zSXZdf1wvVuZrD0508ims5zQsqN9EEUkN/kNuBlxlPDxt9AzgFpxs+b3K9faYHCJSZqe/7vv0xePJzYKKfJSD9RO2gb13XlyxrTShvb5WlX4qYisXjdm6A2HTArZYxr5eI4KHveH9UMhg9CxowUjCqUggkUQsDtG4ub+T9z1wQEtIUVwwb20lfWgT7QKTsy19LSX2UK/VDFllJPm49PVXkgPwbVaQEhSeU7jQ7iUs1U/JIIcF9Svkg1SfiNRnvu5f+5RUv3juUj8lng5QD6K8pZWpOfTCzEju4XsJa8iGBNuYmkDipF9B5MtcqF644FZ7A==,iv:/P9tTEIgs0rHVp4zOxslTDaE5ffsS7igBSaoyO8SfbM=,tag:UGAw2Cz+VJczB6xn2DfHZw==,type:str]
    tls.key: ENC[AES256_GCM,data:Fu7tphTCPAc4kKCqUtptbUC9+4cL148H1v5EP2NJOpA2c6dVlPB64FOxALRLyDaXZ8mUMbditw8lF855gJ6BuO77A8AaOT+W73du8tfcTOdLoSEysQZsJJVOT/KJRTjgPHrnVvEnutU+cvR75fIwQggJLdqFkK5bXUS/mR95tWy8WV//0pd98//Znbw8Yu9x6VbDDURRaL9vWB0aYPXd+viRhatkUhp9IiUXpFT3Nhr9PDmQeAS8ClMj7tMFX6TC9EO0LvxfVaHbUDVmxvcMaMw3K8bb5Rz31Ruhj5pM4MVLBg==,iv:CwzUghhJfIWaB1l0VNwCbTJuv0hqYRLw6a6mY2NuwPQ=,tag:LIdPbHn6pXJQGa7KtjYGag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRlpHL2NxZ3RxcmpLYTRi
            cERRbjBEcGZILzdFaVczT3JyS1FXV0QzRXlZCk92bnhDcHByY3EyRnpFQVBNdm81
            RHZyNXVFMGhUL1FJQzRtdTYzMmVjWjAKLS0tIHpsTzhCaW1LSk5DSkw5b2htR2xO
            YlJhRWUvZ09ZL0hQWmpvTzZrSG9mVHcKmsaQ8GmmuBH18Ql8JSUSPLayeGXQoW5O
            waO78VRqznUI2YEYWFJC87ffgLk9Q01FCYxinmD6UtwP8Ny5v8+9AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T00:40:18Z"
    mac: ENC[AES256_GCM,data:6uIDCEQskPC7qDUvC5xnW/AWHOzcSgaVjysIQ3FFxPFg+QcTx5cNhrkNQTVCrVHsy+vUBjsmzLdT3L0kqE215ofp2wwnuTAdksNBXX7pI4rOox2DRhoTcrVfKpH7cahfBda6QXoI9t27YQrFcJOm5qu9RR0m1z/lk6OCt29KeSA=,iv:YrpxgkHKGhwmJ3QBqoMb4478+V6Sb4Fkc6madPUPH18=,tag:4EN/CAllRS4LYz5Lkgl+kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
