apiVersion: v1
kind: Secret
metadata:
    name: auth
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZghZEtbyxrwBIRVecsxBwYoaPM/eTzwmRXJYDzfxAQrxwFdYqEA=,iv:wFFxKV3T2HJgd1tAaD62RrLhF/m+OYtJvQ54+mJBqSM=,tag:kNr/R7jr5Qv04aJ+T3RxnA==,type:comment]
    #ENC[AES256_GCM,data:Tt/s059TK9gM9VWQNyoji9AiPYE6wnW7ijsbLQLMMe2Jk/fX4iR4iIHzMEyNpdtSlMpEO9MrkDGFQdtz2LxP1RLjGmiLT4CWtR8=,iv:dggecviFw8KiP5ZL4oXX7EWNYQaPNlSgtWSDCx2Mgdc=,tag:hv4dTjCDy2/qZMAdfCY2Ew==,type:comment]
    couchdbUser: ENC[AES256_GCM,data:46W7wzO7gsk=,iv:M190eviWJSK+2gBMHBQ97zXH0Xwj4wxEEz59kLSA5Qo=,tag:37rRD232YumsVIJLRlWgHg==,type:str]
    couchdbPassword: ENC[AES256_GCM,data:dKiKEe5AUeWNcPuil85ZUMzNO6/ftWI64kN2Xk9+,iv:pGX14LvE0Bf/KqxQ4eHNPTNmxzvUZiJ2FogylgavWE8=,tag:rXVgK3800qYyf/Je5orVFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRE50MGxqbE0xQXRneWtx
            a2FzeXRTZnNEOU1JVkhhZG9yblJJV1NWOXlVClhPSGNpWGtCdVlZVmYydlUxZUt2
            T0tUL1lNL1hlK1JMbzFoYUl5aHJJMzQKLS0tIHRpTFFscFVYOG5FLzJWYyt4dW9B
            WGxnY3IvNUdsK3VGL0cwVXBySFZlZDQKzb70Au0JNI9wV+6FTZfRsBUUCvhB+Lov
            4i3RyWGRtX0wVMEwDCegpaPTxmu1nLoyxekTtfrxpllm2UnyLQtVRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T17:35:29Z"
    mac: ENC[AES256_GCM,data:7buu8toGGYeONTMOwMmrpq9HXg+fMQ32Xtt+HEq6+Lqbf3LG/1W9xW95M6wySd4JGjgJ6TL0pdxPnUA+5Z4ZQFsfKd1f4XekPVpGzZaAlghGxPmldj68TWVGSshGFZfkryOIrdbMYkNPloSLFzyMhstbmArGzLDCr72GNjq+b38=,iv:vjUM0pdOrpTMr7W9zemYDlaR9oionmCz5q3mapIg2qM=,tag:RY0e6jzNnqwtSeN20DiMpA==,type:str]
    version: 3.13.3
