apiVersion: v1
kind: Secret
metadata:
    name: mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:1K6d49d1iYuukQ3zeD6h65RpMtVrppxRjO2Iq7bm4CKedyIewRzlaQ1oJMZZ2ue+2VhjXA0wKEk1gYv1JjKRPusWDJ6b,iv:t5Dp+PDNDaXh6m0yFM3zha89qPBvQObXrARys4n9st4=,tag:FyCoJMyKfI1xfxbm63iTKQ==,type:comment]
    #ENC[AES256_GCM,data:u2NLWwxcgePXYzF4PVNAqhQfyUipL1kGOqGoUtrasQZf0kyLFGsUa47U8T4DfrtLs0UyCeOfoZS4Yjl0sJnXAYoGndHdVug=,iv:gc0/Ef3E0FyIHSZ7UkkRX9oalXIa6PATTdDBfFYkG90=,tag:6ECoDiTlS1mK3mnFa3mSQw==,type:comment]
    #ENC[AES256_GCM,data:k/o/KzvICClkCOspYT+fsvbuBB+hlyA3QjaI6oSKoNFSNxed9bwUwrfICnpRfuy6ii1Ft+rZo13rmnYwOn5bBVozHM1i2nI=,iv:piPdIDTk37muLT3RJxkte4MSqP3KH9SSV9UC34JcG9I=,tag:VZOOb2Hdb8ph3GDZxyR0AQ==,type:comment]
    #ENC[AES256_GCM,data:JkLx0h22LwxVSPtHNAlllCYON7CqTGurlaYwNQ+t+vUBJlMiQyBh8YStLmiOllMJOxj3cM15LaoRuw8+Ws783w==,iv:tNHq0SRRaXnJ2YAk+W7hs9z8hPRaDMGCWvVwLtrg+PY=,tag:vjFcCJklk230C0suUaclGQ==,type:comment]
    #ENC[AES256_GCM,data:pxlENaTz92gp+MSk9X39YqYQH4sFlcwRlilPSnUVH6zcjbNkgCgUL3OrTP4pAI7DmLH0KVA2kSK0xUkMO01uH49Ag1i6,iv:UQIq0xrtlvQg1lUFJyqe7Ty1tKVGkBH813TpjN94WZY=,tag:BeVqAyyC0IHEjS4QdfJrqA==,type:comment]
    #ENC[AES256_GCM,data:OsAgnQITSqXDgKsFjs8ccS+v/IFm+ao3R+I65YWLv3lgELfHXlwBIfhEu/Qj7A==,iv:8xYoeVt5yD3z1PJlu9LEu0T2QXXZX9GjkxNYoWz9REo=,tag:Grl6GN7A7cc1PKt6Ms1Byw==,type:comment]
    #ENC[AES256_GCM,data:jM769stud9nxy1XBHl5rq/HEWn2nbme+2AKtutYCbjNTnH94B6LjEWjb5xt74FNNwT0esRsDjR9WhNdx7WmlTZ2IyDOw,iv:KvyaRlmElaQDY8W+bEM33r780JZK/O+h7z/gfS6BbAw=,tag:LIaKP5C4YwtNrdlKrOgtGA==,type:comment]
    username: ENC[AES256_GCM,data:W9DkOvgGipH0NVdVex8=,iv:wjMXxtnz0I5oCV1CdRu3MSwIPj16ifytr+nPTwD7moo=,tag:UtCZlu0455pEYzYN7cISFw==,type:str]
    password: ENC[AES256_GCM,data:F4O1Hu2bsi3/8zQsAzGLirBGkx9TGzFt,iv:5aWZFsW2FhLvV7OqglZUUhQWqEioWGPPPLb1zcGT5Mo=,tag:YnlRLJarhsMogfUDC2t/ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckhWZ3dHRDROckVYR3Fw
            NThhYW15d044RXp4YWI2b1JnWFVDTHJYOFJBCjBKanVjeS9mVEFUaGhRMVp3cllJ
            ZVQ3a3VjVHhYSXNpeHNYcEh4S0NJbEUKLS0tIFcrVmVuczcrQUd3OFduNmVRVno3
            Rk9pcURab2QxVElwblo2UHhTdFBpb2MK4rnv7VqqdekWZ1UUNi2z3HsZmu6/uYOa
            g2Gst6nN5QAhVsf5qKX0vFdwdl/niyl1xbVC83NgccYcs27jfe8Ijw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T02:48:16Z"
    mac: ENC[AES256_GCM,data:EY0SgKdXblhXEjXQfLf9hzcpvCpFGOOmN/Nt0PTSjKbuMbflVx96SJQPysRKENner0mzhKn3ODbaMsuxAKuPJNHbeSk8+wOdhG03hmZ1DvNeK2Tp0TbqyhDBX9lALU4JyiWSf4dJPuA8sNLjHP0aIcaXPadlnlpMk1slrOFZ+ug=,iv:a4fuQYuz8CEDKT5mALlSYq0jVhRgIg+zskI1ElMVL7k=,tag:+tUSkJo5KOstkzguOuLvww==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: api-keys
type: Opaque
stringData:
    #ENC[AES256_GCM,data:X+Zr211kA2UJyD/Xgw4Ncq8qMTXVlgfGTBVdTt4qP+lNsUDLVN3fXdZDYMpdIV8eEgHiD5C4aALDz8+dUCQzY27U9lQuUw==,iv:zwIwvKnTHgqDLUeqNrIma1K8g9u9YVctIrb19TLcSr8=,tag:vOXnjfk2BT97ciUTP+SAjQ==,type:comment]
    #ENC[AES256_GCM,data:tFrYu0V0sEGepKv7HkbCI2BEBnJarCQqTppqhwJ5hi7y9dIzVB3qH43t,iv:hFu0LZsiYPqO4TvNSS3lm9oMh3U1AN74/v6Sp9O6uY8=,tag:a7rK3VExUTXZgj15rqhzsg==,type:comment]
    secrets.yaml: ENC[AES256_GCM,data:Odcr4FeXikKSSpJfAy76DH+Hq+0Bsxt7oM5PMgzx+OqswyieiWLVZbyA++/vYQjhMlfWKPO5tyy+vMJyb8kmtCnU,iv:gBZ0b+fxdYgUVYX3nuCAFpX4AoTN8GByvSMs1BQD7gY=,tag:5qxA5+vkt40Gdt6VDPAAcQ==,type:str]
    #ENC[AES256_GCM,data:A1F1jot7bykimTJEuJtwKVcL6Tk3dVyiLv1OW9Dt1nvBlze2XefhiqDhH9oo6rUNgDE/hq6yAZb5Sezn07c=,iv:OelCH7uQdZT7NQgATZeGRcuRmzMfxm0puco4U0xkV30=,tag:HG68Glh84AWkEs0+FuYJSA==,type:comment]
    #ENC[AES256_GCM,data:/MZEfFGUscHZB0UAVUD5XfSVZSwBM0nsFCW4YPyQ2roHu594hbb6jPkj1giS1xKfNANjQtfRh8ps8wc6UZ4=,iv:jNbRAkoVxqgBYRBstmhYlunDH8GfRJyJuqb8H3nlBC0=,tag:v2SxYaKxWo6EPbM3IAy12Q==,type:comment]
    homeboxApiKey: ENC[AES256_GCM,data:0kQq7pH0N3uIn1+0zyyjyENa3wIURgpilZ99m2wAJFHmxbZpTXPTocoZCyaubg==,iv:qmz2lnjGHozM/23SD24+0FaKVppYkLQ+SUciRbx80QU=,tag:XjAGVV/yqRilnrY+zh/Ckg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckhWZ3dHRDROckVYR3Fw
            NThhYW15d044RXp4YWI2b1JnWFVDTHJYOFJBCjBKanVjeS9mVEFUaGhRMVp3cllJ
            ZVQ3a3VjVHhYSXNpeHNYcEh4S0NJbEUKLS0tIFcrVmVuczcrQUd3OFduNmVRVno3
            Rk9pcURab2QxVElwblo2UHhTdFBpb2MK4rnv7VqqdekWZ1UUNi2z3HsZmu6/uYOa
            g2Gst6nN5QAhVsf5qKX0vFdwdl/niyl1xbVC83NgccYcs27jfe8Ijw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T02:48:16Z"
    mac: ENC[AES256_GCM,data:EY0SgKdXblhXEjXQfLf9hzcpvCpFGOOmN/Nt0PTSjKbuMbflVx96SJQPysRKENner0mzhKn3ODbaMsuxAKuPJNHbeSk8+wOdhG03hmZ1DvNeK2Tp0TbqyhDBX9lALU4JyiWSf4dJPuA8sNLjHP0aIcaXPadlnlpMk1slrOFZ+ug=,iv:a4fuQYuz8CEDKT5mALlSYq0jVhRgIg+zskI1ElMVL7k=,tag:+tUSkJo5KOstkzguOuLvww==,type:str]
    version: 3.13.3
