apiVersion: v1
kind: Secret
metadata:
    name: mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jADY1DkVgg43BxNWEzKUTeBd0GTyhR4fEFTPlEUmmPVm+VAlyQCVPoivBQOiUxPNBr/PXifJ6fWch8xsC5YiAPU1auJG,iv:DwCHcZ3VfLanElWQBTnlPtoPieHSvKCEqtw9OHVqOJA=,tag:7B+VXug8r4nojOJz2kC9gg==,type:comment]
    #ENC[AES256_GCM,data:u0wJs8AcLWHzyMUxDyWQXy+sJYEkQ91H1cQ5Z2D7+QmUUTu2BnCfUsJQHCjmAhE6R1yEbRQK5LyTT/FjjNXujl9ThKeL8Ro=,iv:qjXgnHf9tKOsj79K3FLpss5AukimBNZJRFz4wBzP2zE=,tag:1YS4tRmaeH5A9ElAijESVw==,type:comment]
    #ENC[AES256_GCM,data:FR7vD16V4vEvRKlGjCDTSlRIEaxgVhlQoYzUmyOk0KI+BVU8ozKo+S9OI2e2YiEEh2wAH8kXpWu29I/Rxbo1pshxXqQIusg=,iv:fQLZOpqoM3Nb91+BriOeSccp253TJLNAl6NMCjWvM08=,tag:usR9lGFP0KpfdUMBNuAXYw==,type:comment]
    #ENC[AES256_GCM,data:8Be0g/yUbwVBLtm7+gk/nAvHBSlGReXQwqJk+vhcgraocqTNLgt9PuS25Viym9u8tvA8ej11MCUEhOYrVk2z5g==,iv:16QaFuBXhzLyWH171ORAV10CJgtwYir/1+vxJhYOWRw=,tag:ei8Rb9NFyzzS9pl2yMj94Q==,type:comment]
    #ENC[AES256_GCM,data:1jb6ewxghAHgwYp8ljaFbeLkriMmPLIesGf+F+6hEOp/u6++rJ67NuGhs4S3CFEFwOQce/WyGr82aBXicguQLe/dhD/3,iv:T++sc3/lp6ZMh/2kg4bYb1Omg/37BOJ60OzhHFHQg/U=,tag:BVrH1j2njMX30q6PPZHHMg==,type:comment]
    #ENC[AES256_GCM,data:BNFcbMYK4i486PualIzUvXBb6DwemdVXzjKcuMgUmO57jItNIVPz5zcUkMftyQ==,iv:z7zcam6nXwQn089qf9ajzcV8f6BJX7LH8xq2EhPOC/I=,tag:BuT2JtHEwcBhStXAxnfeaw==,type:comment]
    #ENC[AES256_GCM,data:pfJzHrP2f/0fx+eykeqpKNNkYe9LyWPZ+DLM51APnd/sx9Cv2yPXoljjroRHQ+hLQ7Pa0dFc2gUWx9aDWuncvZ+ot4be,iv:aHaaGW7sn3PkonriNFoftF68u6CWp/5cWDnlqRD+MnU=,tag:FgLoEKtQxvw29ipx8ZcUoA==,type:comment]
    username: ENC[AES256_GCM,data:1LvRPF7kykPNSIKZGls=,iv:v/tkF9bIxOPyy0F8LJEj1cHahviliAqJiPqEiGBsbF0=,tag:C95ewQ2iwWlVGjsCiSJnlg==,type:str]
    password: ENC[AES256_GCM,data:9RbNIpYBPRmTOBooepOUXQMzWFdmi+UJ,iv:LMcataLb9ScOgD6A/8/XTbManqqG8qDiWzoHrK4BJIE=,tag:FnpZCZwVYvekEH7DwHv/+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQitCSnVIcEZESTlmTnRh
            ZGZJakd4TlRQd2Uzc0FzSmI3a1dCVUNESEVrCnN4VHhvUm5GeVJlNzQxbHllRmx0
            c3RMKzVWNkQ5R09sdjI3azVJcDJkQUEKLS0tIG5XMytSOUNVQ1RaYlIvWnkyV2h6
            UFJxektJZkx2bFdORVd0ZmNKdEV0NHMK1acPeNsWCpZTYENHVuNX8komH/13Zt1b
            o1NfKVgeBb0IQY7GFy79bBCyb61UOP/aNldQ24p5q85OCFI06Rp4lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T01:04:25Z"
    mac: ENC[AES256_GCM,data:Hb5DO6kZk11LnpWLAk/UEHbSKuWEMveGQ4aXo+6xsB0fJnb6msshAc7YvpPHp8Fm/Gey3upWTSsCILD4mOTGmsL7RJPlcK69a9yaMlIkjpXJTvaEQRYktusAiMvP0ok1A1/8kFLy/b+x4wbIgnUK8U4qq+/OyXAiyhVSxgsAceA=,iv:VB6L4Sl8SVz4VjDVunMqDsUOr4g9NJtmP1S0cOlY2hA=,tag:kjtAjWCdsC8uFDSC3Pin0g==,type:str]
    version: 3.13.0
