apiVersion: v1
kind: ConfigMap
metadata:
    name: settings
data:
    configuration.yaml: ENC[AES256_GCM,data:GkwGUj8sRf9nl4wCw1ReatwBDbEyeUvz4gimCNbCEGMaHo1FvXvIL2vZueYIwBbBnmMfCBZIPsb2u5oyHUREZVIszAbCYYIY+OIZ4oFhd0dsiw4TaDNjSwBPsRkTuMEJKo6QSVioLmKoglnVbzpqTNwCzcx4F89Sx4tN8+cwZ2NOCeOXBSangNAr/07tlkcB9qDQNWXgRF0PW32C7Noz2rDjl9A4fPgS0AN8aAkK9q1fYlCMOzwqVXmjMvQFpwstHQsT66LkrGv8e5CZRNol8ZmTFfGTwH8iF+ZQqWMKjPpCqQdH5+KgQFypCfm0N0NYJ/BIubyV+4TKE+LvyGfDoaxV2WpGhSknkMgYLJblOA9CG+Vw/9we83bZM4VSd7S8qclrEd6bWb/SA2k35EvT1hMF47lNybRGZaVlEufepkPrvZ1MBRywvHBTFun6s6vLILgOR2NL88sM5jIQ4l42AsDhyGynNc4e1U5RRbKg8QNWL/iGp375Ry9Qd3MdI9bTCVh40hU1ekh0lGqD1Ei8Pg3sb0lJAkmWdXh86YJCXJI20nrrbFXiseDmOUIy/jaBGrpgwszCKHdFRv1db1uk+LzE+V9UL0WTYoyE1jmauoo1fg/uQbkRqYWFAeKyvgS2NyKBUlKA0z+Gtw8qXpfTpwPj5lhJsW+1W4kiA3lHB/UMCAsmz7obCVoRtojeS3X8wx0zWD/R,iv:DwrHzJtn1dEJmqIRKQqzTEutILfQeF/hU11pExAEhKM=,tag:5BjHK1L7CTWxPHvSgy/4fw==,type:str]
    devices.yaml: ""
    groups.yaml: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnKzd6K2JON2J3Q1NrQm1n
            RXo5QUY3VENLU1ZJUXlISjJyYnR6d0pkZGhVCnUvdEJsL3JIaEhIbG9CYkxKclkx
            TDlGeFQyTFVrVVpHaWc2RFpULzdXZDgKLS0tIDRaRjRaejU4ODBianFDWTRLQkJy
            bWdTeVFqL1Zqa0F6S0tXUm9JQUd2cjQKSjGTDf5lpKcY2WaOAHLXpKz5xCmd+/dM
            Y9Of+L9ZTzjOea5ygbHrItaKOpBrcIft/RTBE9TwY6FwYS8waJCwxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T17:34:50Z"
    mac: ENC[AES256_GCM,data:Id12k2k0lKrmdlSb1dxv41JFRQfDXH6Ln8eeh80wlzFoCl3ax7nTbAFWGqE0+OMTiebfPMxUg/R7aU6PmfvdmXNg4UUTE0Stc2p2U6yR4Xa0Pf761TvKwtmlmFjTBw1j9v0TmOyNYnwl33gHZ3fw8f9bMU862EMm/TxJeu842ek=,iv:yPBVaF3EgcR0ne/E6WhbZGdU80UoD+wTpDMrmnKTylg=,tag:uVEiz3Z55ZYg5HDGC7toLg==,type:str]
    version: 3.13.0
