apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../webapp/base
  - configMap.yaml

namePrefix: zigbee2mqtt-

labels:
  - includeSelectors: true
    pairs:
      app: zigbee2mqtt
      app.kubernetes.io/name: zigbee2mqtt

components:
  - ../../webapp/components/httproute
  - ../../webapp/components/pvc

images:
  - name: my-app
    newName: koenkk/zigbee2mqtt
    newTag: "1.38.0"

patches:
  - target:
      kind: HTTPRoute
      name: route
    path: patches/httproute-add-homepage-annotations.yaml
  - target:
      kind: Deployment
      name: deploy
    path: patches/deploy-add-config-init.yaml
