apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-home

commonLabels:
  app: zigbee2mqtt
  app.kubernetes.io/name: zigbee2mqtt
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: dev-team

resources:
  - configMap.yaml
  - deploy.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml

patches:
  - target:
      kind: Namespace
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: smart-home
