apiVersion: v1
kind: Secret
metadata:
    name: mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lDOYjefp0cKNh+p3dkotQCboOGtmJTXXMvajMXxWNV/2ArfZBdEET/OohXsAjzy/pYFwjE0fWdXSvxTKwa0CmryuhL+KdA==,iv:I2JM7Yz8Fro3/Z5/FSP/5iRFgBjd/KYz0WbDDMHx/e0=,tag:QU+GceTiP4/AU7WA1HxlKQ==,type:comment]
    #ENC[AES256_GCM,data:W0DjCDua/RWQiHfiMJkhfOKoUfVmODeq7YVy8bCAuGGuS1dOlx9CcfkXdbHXSvOdCnoZi5LtPfrTAbVOTA==,iv:FM5DXX6OaGSm8YQFatDrl1mmE6zGcJxIonazo1Cp3zk=,tag:QXs59ErwG3iR+q4gbv64pw==,type:comment]
    username: ENC[AES256_GCM,data:Viod7sD2A4amXTXigQ==,iv:X2LDQVXqEHjd/tkP4eRDl5G1gHiSkKKntl+kgbNMazg=,tag:Zg1t+o2miFZiewkFgXdXww==,type:str]
    password: ENC[AES256_GCM,data:NpXwSBJsZkxIgLd4fUHVgO/56TYT11npSBbsjtkjR/s=,iv:4QmbC3wpDywunlQAKK7aBw/vd2ofq4MCVOXQY72eDjg=,tag:VkmFRD8FvSa8n+eBHdbHkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VDQ0c1VCb21HZDJZNVEy
            WWpRRzFXUk1OSDJqRHhTR00yR0o5ZFpndmxrCnhkdGpSQm1jNlAySlBUN3pwUU1V
            VGN1MWZRQ3FwbDVKTjgrVytGaW9IQVEKLS0tIGdjMlE5eXRnYjZXUnhCQWFjVlFV
            L3J4YmgrTm4zbU5Pa3A0bCtVaEJoR00K2Y8sFVtgk40990ujUDuP9OYQVtly6E9b
            Fn26Rz2gHYCxMT8G55Zd/5AS/h2st4bUEQmTmI9k6ksOftyEy0n+6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T16:45:39Z"
    mac: ENC[AES256_GCM,data:PXWdtO1tPlhJki+uCyeF9Iqrb4O9O17NXhWlQ+Pe2EPRiOIpydnbkQcriK1MfQYE6ZqMd+OiKXmp2rJSCPAAngVA1sxmd23KfD8MRHYucVu43NWjwuUIQvglpDV24j4o6XbNVdjKcXVf4an739d7tDdTk1YHNeA7VAHjWfiIK2E=,iv:qK6Z4+9XyywLZdA6SfsRj08v5hz1s5QKaTlo0xYF+0g=,tag:hIwsJl7JorkXUb9yQ18O6w==,type:str]
    version: 3.13.3
