apiVersion: v1
kind: Secret
metadata:
    name: mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lDOYjefp0cKNh+p3dkotQCboOGtmJTXXMvajMXxWNV/2ArfZBdEET/OohXsAjzy/pYFwjE0fWdXSvxTKwa0CmryuhL+KdA==,iv:I2JM7Yz8Fro3/Z5/FSP/5iRFgBjd/KYz0WbDDMHx/e0=,tag:QU+GceTiP4/AU7WA1HxlKQ==,type:comment]
    #ENC[AES256_GCM,data:W0DjCDua/RWQiHfiMJkhfOKoUfVmODeq7YVy8bCAuGGuS1dOlx9CcfkXdbHXSvOdCnoZi5LtPfrTAbVOTA==,iv:FM5DXX6OaGSm8YQFatDrl1mmE6zGcJxIonazo1Cp3zk=,tag:QXs59ErwG3iR+q4gbv64pw==,type:comment]
    username: ENC[AES256_GCM,data:Viod7sD2A4amXTXigQ==,iv:X2LDQVXqEHjd/tkP4eRDl5G1gHiSkKKntl+kgbNMazg=,tag:Zg1t+o2miFZiewkFgXdXww==,type:str]
    password: ENC[AES256_GCM,data:FgYJaWJyrDQceidJ2sLEpSU1bR2cgMQ/XlN2xRUT9g==,iv:qGVkZuBKScuXHtquz0VidtjXKcY3dQaxReSRHcq1OhU=,tag:wtcQIp6ukVpBOu8QiYG9Ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VDQ0c1VCb21HZDJZNVEy
            WWpRRzFXUk1OSDJqRHhTR00yR0o5ZFpndmxrCnhkdGpSQm1jNlAySlBUN3pwUU1V
            VGN1MWZRQ3FwbDVKTjgrVytGaW9IQVEKLS0tIGdjMlE5eXRnYjZXUnhCQWFjVlFV
            L3J4YmgrTm4zbU5Pa3A0bCtVaEJoR00K2Y8sFVtgk40990ujUDuP9OYQVtly6E9b
            Fn26Rz2gHYCxMT8G55Zd/5AS/h2st4bUEQmTmI9k6ksOftyEy0n+6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T02:05:58Z"
    mac: ENC[AES256_GCM,data:xCk1RM4MvIw4ISnswjgDeUOuiVsc7NMeIEpBZHZjy5R3SJkgDq0LEfh8g36NmQz7n3GaWhodQRSh0u8Dkoeny+BraTlEIwcrR5T/HSJgBaxtcRE1qqoWTDl1M5XpsGqgbYPkjxVixQpotfV+rnEawuygte+OgOTzRKHpu3DPZAU=,iv:fwoUGx9QWC3Y+gLkouodvEc6WoSQweDJ4+h984Y70hE=,tag:EwpumNPZFUQgX/gOM08fqQ==,type:str]
    version: 3.13.3
