apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-base-config
    namespace: home-automation
    labels:
        app.kubernetes.io/name: mosquitto
data:
    mosquitto.conf: ENC[AES256_GCM,data:+JWKguiSE6z054ryvVDn/UkbVUPGRYxWQMpi4VaTQ69z1H1hrfIWIHeTe7bw6E/ct0rl/ekQj3T0CgoKmjJ74GajUN66YzEcxKbzcLhTfs28dq/CA89LEmuE/JLNM4TwHNuwC5fUmSD+obHkAToIOXGUhzcNGalLESyWea2rIFxKdOHfP5DrRak=,iv:By5xw16jK1W3v0M2fAACwMUSBcsDjsv42X9qjPFL23Y=,tag:aclJ/41CW//80JIdiDWRjQ==,type:str]
    password_file: ENC[AES256_GCM,data:L/r1ocE4Lq9rZIr1S3vfWEW8tr5S9iJx69C254WnfEOS3wdyL1cidluxC1TWpuoOm0dBN5ZRigKcyD6meLSG+zIy4yzezJURYl3AJTFLIo3RVqFrhi9R6KO8wgcBMpCa331iIDhip5CmZUpy99PxGrUCguY0ylqQnzUKWzoZhxJ9qgORfCiGjBR6J7FGMqkcdTs6lI+3I4qWufW/fdLRirE+hRtBqJTjJD/uOruAuQ+HNO08DyBvrX/YZhnKe94loWbScgJKnKkAXyZxhyBpePmGZpMZIcUtiu4XUvEy2XuB4fOjSnFop4Uw8s4YC9qhto3KYK0sg5A+zVpLiPAj,iv:0bZUeiDU5aLW12ZK92XjyZN4LFOh2S7A8rxiQ4VN3iA=,tag:4dXX4qDQYieWPpCUPDIwOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tszh09s5hr9hzjdy8enq7uncz9p2z09hsvky2dn25vudr4cx37s6k5n9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ1F3WFQzRE1VVExFeThv
            VExmV2k4dTRJNGk0Q2QwM3lYSThucjdrcTJnCm9IMDVQMy9ZemRSaWFYUWpaV2FC
            Zy8rMmJQRDJxcjk4OWZocFlHanlWWlEKLS0tIEovSWNHUmQzWVhuaUxXNUkyOFBO
            ZlNQUnFlWGtwOFBCNUFKZ0JUWUljTGsKLUtt9+Phibjd+HI6PvtChnc2qHssqYtM
            n7kk1isgv/8yL12GAkkwDwxkNNoLkP2T+95N274GFI9sLriHtmciDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T01:52:38Z"
    mac: ENC[AES256_GCM,data:WSZy0SBIhaTu9mW4iMSe+1TTJp0wp8wp5vQ4vdw4X3RGO9L9Uev+ggdr8jeA2sMaK9Q9j/jFVard89miVkWM5lCPJdNbAZzg7gjbG3mP0md+zoghIk5lj7sjB3mNq4cRs2jPYKNV1/GOvlxxGE8GAIhYyrJrDsRob6cnV4wzt3E=,iv:dW96oel7Ezj8D3ogaB4ezp5vOyPJ5mlhzRvFwMs2au0=,tag:nDpwzx1gzUZNgI0td8WFCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
