apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - configMap.yaml
  - namespace.yaml
commonLabels:
  app.kubernetes.io/name: mosquitto
  app: mosquitto
