name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@16602fa989daa99762f1c6d1186ae2ad1c735815  # v2.9.3
      - name: Check for updates
        id: update
        run: |
          flux install \
            --export > ./kubernetes/clusters/orion/flux-system/gotk-components.yaml

          VERSION="$(flux -v)"
          echo "flux_version=$VERSION" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@d4f3be6ce6f4083b7ac7490ab98b48a62db1ee41  # v7.0.10
        with:
          branch: update-flux
          commit-message: Update to ${{ steps.update.outputs.flux_version }}
          title: Update to ${{ steps.update.outputs.flux_version }}
          body: |
            ${{ steps.update.outputs.flux_version }}
